package protocol

type Protocolipv6stats struct {
	Clearstats                     string `json:"clearstats,omitempty"`
	Icmpv6error                    int    `json:"icmpv6error,omitempty"`
	Icmpv6rtthsld                  int    `json:"icmpv6rtthsld,omitempty"`
	Icmpv6unspt                    int    `json:"icmpv6unspt,omitempty"`
	Ipv6badcksum                   int    `json:"ipv6badcksum,omitempty"`
	Ipv6errhdr                     int    `json:"ipv6errhdr,omitempty"`
	Ipv6errrxhdr                   int    `json:"ipv6errrxhdr,omitempty"`
	Ipv6errrxpkt                   int    `json:"ipv6errrxpkt,omitempty"`
	Ipv6fragpktsforwardrate        int    `json:"ipv6fragpktsforwardrate,omitempty"`
	Ipv6fragpktsprocessnoreassrate int    `json:"ipv6fragpktsprocessnoreassrate,omitempty"`
	Ipv6fragpkttoobig              int    `json:"ipv6fragpkttoobig,omitempty"`
	Ipv6fragrxpktsrate             int    `json:"ipv6fragrxpktsrate,omitempty"`
	Ipv6fragtcpreassembledrate     int    `json:"ipv6fragtcpreassembledrate,omitempty"`
	Ipv6fragtotpktsforward         int    `json:"ipv6fragtotpktsforward,omitempty"`
	Ipv6fragtotpktsprocessnoreass  int    `json:"ipv6fragtotpktsprocessnoreass,omitempty"`
	Ipv6fragtotrxpkts              int    `json:"ipv6fragtotrxpkts,omitempty"`
	Ipv6fragtottcpreassembled      int    `json:"ipv6fragtottcpreassembled,omitempty"`
	Ipv6fragtotudpreassembled      int    `json:"ipv6fragtotudpreassembled,omitempty"`
	Ipv6fragudpreassembledrate     int    `json:"ipv6fragudpreassembledrate,omitempty"`
	Ipv6fragzerolenpkt             int    `json:"ipv6fragzerolenpkt,omitempty"`
	Ipv6icmpnarxrate               int    `json:"ipv6icmpnarxrate,omitempty"`
	Ipv6icmpnatxrate               int    `json:"ipv6icmpnatxrate,omitempty"`
	Ipv6icmpnsrxrate               int    `json:"ipv6icmpnsrxrate,omitempty"`
	Ipv6icmpnstxrate               int    `json:"ipv6icmpnstxrate,omitempty"`
	Ipv6icmprarxrate               int    `json:"ipv6icmprarxrate,omitempty"`
	Ipv6icmprstxrate               int    `json:"ipv6icmprstxrate,omitempty"`
	Ipv6icmprxrate                 int    `json:"ipv6icmprxrate,omitempty"`
	Ipv6icmptxrate                 int    `json:"ipv6icmptxrate,omitempty"`
	Ipv6landattack                 int    `json:"ipv6landattack,omitempty"`
	Ipv6nextheadererr              int    `json:"ipv6nextheadererr,omitempty"`
	Ipv6routembitsrate             int    `json:"ipv6routembitsrate,omitempty"`
	Ipv6routepktsrate              int    `json:"ipv6routepktsrate,omitempty"`
	Ipv6rxbytesrate                int    `json:"ipv6rxbytesrate,omitempty"`
	Ipv6rxpktsrate                 int    `json:"ipv6rxpktsrate,omitempty"`
	Ipv6toticmpnarx                int    `json:"ipv6toticmpnarx,omitempty"`
	Ipv6toticmpnatx                int    `json:"ipv6toticmpnatx,omitempty"`
	Ipv6toticmpnsrx                int    `json:"ipv6toticmpnsrx,omitempty"`
	Ipv6toticmpnstx                int    `json:"ipv6toticmpnstx,omitempty"`
	Ipv6toticmprarx                int    `json:"ipv6toticmprarx,omitempty"`
	Ipv6toticmprstx                int    `json:"ipv6toticmprstx,omitempty"`
	Ipv6toticmprx                  int    `json:"ipv6toticmprx,omitempty"`
	Ipv6toticmptx                  int    `json:"ipv6toticmptx,omitempty"`
	Ipv6totroutembits              int    `json:"ipv6totroutembits,omitempty"`
	Ipv6totroutepkts               int    `json:"ipv6totroutepkts,omitempty"`
	Ipv6totrxbytes                 int    `json:"ipv6totrxbytes,omitempty"`
	Ipv6totrxpkts                  int    `json:"ipv6totrxpkts,omitempty"`
	Ipv6tottxbytes                 int    `json:"ipv6tottxbytes,omitempty"`
	Ipv6tottxpkts                  int    `json:"ipv6tottxpkts,omitempty"`
	Ipv6txbytesrate                int    `json:"ipv6txbytesrate,omitempty"`
	Ipv6txpktsrate                 int    `json:"ipv6txpktsrate,omitempty"`
}
