package protocol

type Protocolhttpstats struct {
	Clearstats                        string `json:"clearstats,omitempty"`
	Http10requestsrate                int    `json:"http10requestsrate,omitempty"`
	Http10responsesrate               int    `json:"http10responsesrate,omitempty"`
	Http11requestsrate                int    `json:"http11requestsrate,omitempty"`
	Http11responsesrate               int    `json:"http11responsesrate,omitempty"`
	Httpchunkedrequestsrate           int    `json:"httpchunkedrequestsrate,omitempty"`
	Httpchunkedresponsesrate          int    `json:"httpchunkedresponsesrate,omitempty"`
	Httpclenrequestsrate              int    `json:"httpclenrequestsrate,omitempty"`
	Httpclenresponsesrate             int    `json:"httpclenresponsesrate,omitempty"`
	Httperrincompleteheaders          int    `json:"httperrincompleteheaders,omitempty"`
	Httperrincompleterequests         int    `json:"httperrincompleterequests,omitempty"`
	Httperrincompleterequestsrate     int    `json:"httperrincompleterequestsrate,omitempty"`
	Httperrincompleteresponses        int    `json:"httperrincompleteresponses,omitempty"`
	Httperrincompleteresponsesrate    int    `json:"httperrincompleteresponsesrate,omitempty"`
	Httperrlargechunk                 int    `json:"httperrlargechunk,omitempty"`
	Httperrlargecontent               int    `json:"httperrlargecontent,omitempty"`
	Httperrlargectlen                 int    `json:"httperrlargectlen,omitempty"`
	Httperrnoreusemultipart           int    `json:"httperrnoreusemultipart,omitempty"`
	Httperrnoreusemultipartrate       int    `json:"httperrnoreusemultipartrate,omitempty"`
	Httperrrfc7230desynctlente        int    `json:"httperrrfc7230desynctlente,omitempty"`
	Httperrrfc7230desynidenticalctlen int    `json:"httperrrfc7230desynidenticalctlen,omitempty"`
	Httperrrfc7230desynmultictlen     int    `json:"httperrrfc7230desynmultictlen,omitempty"`
	Httperrserverbusy                 int    `json:"httperrserverbusy,omitempty"`
	Httperrserverbusyrate             int    `json:"httperrserverbusyrate,omitempty"`
	Httpgetsrate                      int    `json:"httpgetsrate,omitempty"`
	Httpnoclenchunkresponsesrate      int    `json:"httpnoclenchunkresponsesrate,omitempty"`
	Httppostsrate                     int    `json:"httppostsrate,omitempty"`
	Httprequestsrate                  int    `json:"httprequestsrate,omitempty"`
	Httpresponsesrate                 int    `json:"httpresponsesrate,omitempty"`
	Httprxrequestbytesrate            int    `json:"httprxrequestbytesrate,omitempty"`
	Httprxresponsebytesrate           int    `json:"httprxresponsebytesrate,omitempty"`
	Httptohersrate                    int    `json:"httptohersrate,omitempty"`
	Httptot10requests                 int    `json:"httptot10requests,omitempty"`
	Httptot10responses                int    `json:"httptot10responses,omitempty"`
	Httptot11requests                 int    `json:"httptot11requests,omitempty"`
	Httptot11responses                int    `json:"httptot11responses,omitempty"`
	Httptotchunkedrequests            int    `json:"httptotchunkedrequests,omitempty"`
	Httptotchunkedresponses           int    `json:"httptotchunkedresponses,omitempty"`
	Httptotclenrequests               int    `json:"httptotclenrequests,omitempty"`
	Httptotclenresponses              int    `json:"httptotclenresponses,omitempty"`
	Httptotgets                       int    `json:"httptotgets,omitempty"`
	Httptotnoclenchunkresponses       int    `json:"httptotnoclenchunkresponses,omitempty"`
	Httptotothers                     int    `json:"httptotothers,omitempty"`
	Httptotposts                      int    `json:"httptotposts,omitempty"`
	Httptotrequests                   int    `json:"httptotrequests,omitempty"`
	Httptotresponses                  int    `json:"httptotresponses,omitempty"`
	Httptotrxrequestbytes             int    `json:"httptotrxrequestbytes,omitempty"`
	Httptotrxresponsebytes            int    `json:"httptotrxresponsebytes,omitempty"`
	Httptottxrequestbytes             int    `json:"httptottxrequestbytes,omitempty"`
	Httptottxresponsebytes            int    `json:"httptottxresponsebytes,omitempty"`
	Httptxrequestbytesrate            int    `json:"httptxrequestbytesrate,omitempty"`
	Httptxresponsebytesrate           int    `json:"httptxresponsebytesrate,omitempty"`
	Spdystreamsrate                   int    `json:"spdystreamsrate,omitempty"`
	Spdytotstreams                    int    `json:"spdytotstreams,omitempty"`
	Spdyv2streamsrate                 int    `json:"spdyv2streamsrate,omitempty"`
	Spdyv2totstreams                  int    `json:"spdyv2totstreams,omitempty"`
	Spdyv3streamsrate                 int    `json:"spdyv3streamsrate,omitempty"`
	Spdyv3totstreams                  int    `json:"spdyv3totstreams,omitempty"`
}
