package protocol

type Protocoltcpstats struct {
	Clearstats                                  string `json:"clearstats,omitempty"`
	Pcbtotzombiecall                            int    `json:"pcbtotzombiecall,omitempty"`
	Pcbzombiecallrate                           int    `json:"pcbzombiecallrate,omitempty"`
	Tcpactiveserverconn                         int    `json:"tcpactiveserverconn,omitempty"`
	Tcpclientconnopenedrate                     int    `json:"tcpclientconnopenedrate,omitempty"`
	Tcpcltfinrate                               int    `json:"tcpcltfinrate,omitempty"`
	Tcpcurclientconn                            int    `json:"tcpcurclientconn,omitempty"`
	Tcpcurclientconnclosing                     int    `json:"tcpcurclientconnclosing,omitempty"`
	Tcpcurclientconnestablished                 int    `json:"tcpcurclientconnestablished,omitempty"`
	Tcpcurclientconnopening                     int    `json:"tcpcurclientconnopening,omitempty"`
	Tcpcurserverconn                            int    `json:"tcpcurserverconn,omitempty"`
	Tcpcurserverconnclosing                     int    `json:"tcpcurserverconnclosing,omitempty"`
	Tcpcurserverconnestablished                 int    `json:"tcpcurserverconnestablished,omitempty"`
	Tcpcurserverconnopening                     int    `json:"tcpcurserverconnopening,omitempty"`
	Tcperranyportfail                           int    `json:"tcperranyportfail,omitempty"`
	Tcperranyportfailrate                       int    `json:"tcperranyportfailrate,omitempty"`
	Tcperrbadchecksum                           int    `json:"tcperrbadchecksum,omitempty"`
	Tcperrbadchecksumrate                       int    `json:"tcperrbadchecksumrate,omitempty"`
	Tcperrbadstateconn                          int    `json:"tcperrbadstateconn,omitempty"`
	Tcperrbadstateconnrate                      int    `json:"tcperrbadstateconnrate,omitempty"`
	Tcperrcipalloc                              int    `json:"tcperrcipalloc,omitempty"`
	Tcperrcipallocrate                          int    `json:"tcperrcipallocrate,omitempty"`
	Tcperrclthole                               int    `json:"tcperrclthole,omitempty"`
	Tcperrcltholerate                           int    `json:"tcperrcltholerate,omitempty"`
	Tcperrcltoutoforder                         int    `json:"tcperrcltoutoforder,omitempty"`
	Tcperrcltoutoforderrate                     int    `json:"tcperrcltoutoforderrate,omitempty"`
	Tcperrcltretrasmit                          int    `json:"tcperrcltretrasmit,omitempty"`
	Tcperrcltretrasmitrate                      int    `json:"tcperrcltretrasmitrate,omitempty"`
	Tcperrcookiepktmssreject                    int    `json:"tcperrcookiepktmssreject,omitempty"`
	Tcperrcookiepktmssrejectrate                int    `json:"tcperrcookiepktmssrejectrate,omitempty"`
	Tcperrcookiepktseqdrop                      int    `json:"tcperrcookiepktseqdrop,omitempty"`
	Tcperrcookiepktseqdroprate                  int    `json:"tcperrcookiepktseqdroprate,omitempty"`
	Tcperrcookiepktseqreject                    int    `json:"tcperrcookiepktseqreject,omitempty"`
	Tcperrcookiepktseqrejectrate                int    `json:"tcperrcookiepktseqrejectrate,omitempty"`
	Tcperrcookiepktsigreject                    int    `json:"tcperrcookiepktsigreject,omitempty"`
	Tcperrcookiepktsigrejectrate                int    `json:"tcperrcookiepktsigrejectrate,omitempty"`
	Tcperrdataafterfin                          int    `json:"tcperrdataafterfin,omitempty"`
	Tcperrdataafterfinrate                      int    `json:"tcperrdataafterfinrate,omitempty"`
	Tcperrfastretransmissions                   int    `json:"tcperrfastretransmissions,omitempty"`
	Tcperrfastretransmissionsrate               int    `json:"tcperrfastretransmissionsrate,omitempty"`
	Tcperrfifthretransmissions                  int    `json:"tcperrfifthretransmissions,omitempty"`
	Tcperrfifthretransmissionsrate              int    `json:"tcperrfifthretransmissionsrate,omitempty"`
	Tcperrfingiveup                             int    `json:"tcperrfingiveup,omitempty"`
	Tcperrfingiveuprate                         int    `json:"tcperrfingiveuprate,omitempty"`
	Tcperrfinretry                              int    `json:"tcperrfinretry,omitempty"`
	Tcperrfinretryrate                          int    `json:"tcperrfinretryrate,omitempty"`
	Tcperrfirstretransmissions                  int    `json:"tcperrfirstretransmissions,omitempty"`
	Tcperrfirstretransmissionsrate              int    `json:"tcperrfirstretransmissionsrate,omitempty"`
	Tcperrforthretransmissions                  int    `json:"tcperrforthretransmissions,omitempty"`
	Tcperrforthretransmissionsrate              int    `json:"tcperrforthretransmissionsrate,omitempty"`
	Tcperrfullretrasmit                         int    `json:"tcperrfullretrasmit,omitempty"`
	Tcperrfullretrasmitrate                     int    `json:"tcperrfullretrasmitrate,omitempty"`
	Tcperripportfail                            int    `json:"tcperripportfail,omitempty"`
	Tcperripportfailrate                        int    `json:"tcperripportfailrate,omitempty"`
	Tcperroutofwindowpkts                       int    `json:"tcperroutofwindowpkts,omitempty"`
	Tcperroutofwindowpktsrate                   int    `json:"tcperroutofwindowpktsrate,omitempty"`
	Tcperrpartialretrasmit                      int    `json:"tcperrpartialretrasmit,omitempty"`
	Tcperrpartialretrasmitrate                  int    `json:"tcperrpartialretrasmitrate,omitempty"`
	Tcperrretransmit                            int    `json:"tcperrretransmit,omitempty"`
	Tcperrretransmitgiveup                      int    `json:"tcperrretransmitgiveup,omitempty"`
	Tcperrretransmitgiveuprate                  int    `json:"tcperrretransmitgiveuprate,omitempty"`
	Tcperrretransmitrate                        int    `json:"tcperrretransmitrate,omitempty"`
	Tcperrrst                                   int    `json:"tcperrrst,omitempty"`
	Tcperrrstintimewait                         int    `json:"tcperrrstintimewait,omitempty"`
	Tcperrrstintimewaitrate                     int    `json:"tcperrrstintimewaitrate,omitempty"`
	Tcperrrstnonest                             int    `json:"tcperrrstnonest,omitempty"`
	Tcperrrstnonestrate                         int    `json:"tcperrrstnonestrate,omitempty"`
	Tcperrrstoutofwindow                        int    `json:"tcperrrstoutofwindow,omitempty"`
	Tcperrrstoutofwindowrate                    int    `json:"tcperrrstoutofwindowrate,omitempty"`
	Tcperrrstrate                               int    `json:"tcperrrstrate,omitempty"`
	Tcperrrstthreshold                          int    `json:"tcperrrstthreshold,omitempty"`
	Tcperrrstthresholdrate                      int    `json:"tcperrrstthresholdrate,omitempty"`
	Tcperrsecondretransmissions                 int    `json:"tcperrsecondretransmissions,omitempty"`
	Tcperrsecondretransmissionsrate             int    `json:"tcperrsecondretransmissionsrate,omitempty"`
	Tcperrsentrst                               int    `json:"tcperrsentrst,omitempty"`
	Tcperrsentrstrate                           int    `json:"tcperrsentrstrate,omitempty"`
	Tcperrseventhretransmissions                int    `json:"tcperrseventhretransmissions,omitempty"`
	Tcperrseventhretransmissionsrate            int    `json:"tcperrseventhretransmissionsrate,omitempty"`
	Tcperrsixthretransmissions                  int    `json:"tcperrsixthretransmissions,omitempty"`
	Tcperrsixthretransmissionsrate              int    `json:"tcperrsixthretransmissionsrate,omitempty"`
	Tcperrstraypkt                              int    `json:"tcperrstraypkt,omitempty"`
	Tcperrstraypktrate                          int    `json:"tcperrstraypktrate,omitempty"`
	Tcperrsvrhole                               int    `json:"tcperrsvrhole,omitempty"`
	Tcperrsvrholerate                           int    `json:"tcperrsvrholerate,omitempty"`
	Tcperrsvroutoforder                         int    `json:"tcperrsvroutoforder,omitempty"`
	Tcperrsvroutoforderrate                     int    `json:"tcperrsvroutoforderrate,omitempty"`
	Tcperrsvrretrasmit                          int    `json:"tcperrsvrretrasmit,omitempty"`
	Tcperrsvrretrasmitrate                      int    `json:"tcperrsvrretrasmitrate,omitempty"`
	Tcperrsyndroppedcongestion                  int    `json:"tcperrsyndroppedcongestion,omitempty"`
	Tcperrsyndroppedcongestionrate              int    `json:"tcperrsyndroppedcongestionrate,omitempty"`
	Tcperrsyngiveup                             int    `json:"tcperrsyngiveup,omitempty"`
	Tcperrsyngiveuprate                         int    `json:"tcperrsyngiveuprate,omitempty"`
	Tcperrsyninest                              int    `json:"tcperrsyninest,omitempty"`
	Tcperrsyninestrate                          int    `json:"tcperrsyninestrate,omitempty"`
	Tcperrsyninsynrcvd                          int    `json:"tcperrsyninsynrcvd,omitempty"`
	Tcperrsyninsynrcvdrate                      int    `json:"tcperrsyninsynrcvdrate,omitempty"`
	Tcperrsynretry                              int    `json:"tcperrsynretry,omitempty"`
	Tcperrsynretryrate                          int    `json:"tcperrsynretryrate,omitempty"`
	Tcperrsynsentbadack                         int    `json:"tcperrsynsentbadack,omitempty"`
	Tcperrsynsentbadackrate                     int    `json:"tcperrsynsentbadackrate,omitempty"`
	Tcperrthirdretransmissions                  int    `json:"tcperrthirdretransmissions,omitempty"`
	Tcperrthirdretransmissionsrate              int    `json:"tcperrthirdretransmissionsrate,omitempty"`
	Tcpfinwaitclosedrate                        int    `json:"tcpfinwaitclosedrate,omitempty"`
	Tcprxbytesrate                              int    `json:"tcprxbytesrate,omitempty"`
	Tcprxpktsrate                               int    `json:"tcprxpktsrate,omitempty"`
	Tcpserverconnopenedrate                     int    `json:"tcpserverconnopenedrate,omitempty"`
	Tcpspareconn                                int    `json:"tcpspareconn,omitempty"`
	Tcpsurgequeuelen                            int    `json:"tcpsurgequeuelen,omitempty"`
	Tcpsvrfinrate                               int    `json:"tcpsvrfinrate,omitempty"`
	Tcpsynflushrate                             int    `json:"tcpsynflushrate,omitempty"`
	Tcpsynheldrate                              int    `json:"tcpsynheldrate,omitempty"`
	Tcpsynproberate                             int    `json:"tcpsynproberate,omitempty"`
	Tcpsynrate                                  int    `json:"tcpsynrate,omitempty"`
	Tcptotclientconnopened                      int    `json:"tcptotclientconnopened,omitempty"`
	Tcptotcltfin                                int    `json:"tcptotcltfin,omitempty"`
	Tcptotfinwaitclosed                         int    `json:"tcptotfinwaitclosed,omitempty"`
	Tcptotrxbytes                               int    `json:"tcptotrxbytes,omitempty"`
	Tcptotrxpkts                                int    `json:"tcptotrxpkts,omitempty"`
	Tcptotserverconnopened                      int    `json:"tcptotserverconnopened,omitempty"`
	Tcptotsvrfin                                int    `json:"tcptotsvrfin,omitempty"`
	Tcptotsyn                                   int    `json:"tcptotsyn,omitempty"`
	Tcptotsynflush                              int    `json:"tcptotsynflush,omitempty"`
	Tcptotsynheld                               int    `json:"tcptotsynheld,omitempty"`
	Tcptotsynprobe                              int    `json:"tcptotsynprobe,omitempty"`
	Tcptottxbytes                               int    `json:"tcptottxbytes,omitempty"`
	Tcptottxpkts                                int    `json:"tcptottxpkts,omitempty"`
	Tcptotzombieactivehalfclosecltconnflushed   int    `json:"tcptotzombieactivehalfclosecltconnflushed,omitempty"`
	Tcptotzombieactivehalfclosesvrconnflushed   int    `json:"tcptotzombieactivehalfclosesvrconnflushed,omitempty"`
	Tcptotzombiecltconnflushed                  int    `json:"tcptotzombiecltconnflushed,omitempty"`
	Tcptotzombiehalfopencltconnflushed          int    `json:"tcptotzombiehalfopencltconnflushed,omitempty"`
	Tcptotzombiehalfopensvrconnflushed          int    `json:"tcptotzombiehalfopensvrconnflushed,omitempty"`
	Tcptotzombiepassivehalfclosecltconnflushed  int    `json:"tcptotzombiepassivehalfclosecltconnflushed,omitempty"`
	Tcptotzombiepassivehalfclosesrvconnflushed  int    `json:"tcptotzombiepassivehalfclosesrvconnflushed,omitempty"`
	Tcptotzombiesvrconnflushed                  int    `json:"tcptotzombiesvrconnflushed,omitempty"`
	Tcptxbytesrate                              int    `json:"tcptxbytesrate,omitempty"`
	Tcptxpktsrate                               int    `json:"tcptxpktsrate,omitempty"`
	Tcpwaittodata                               int    `json:"tcpwaittodata,omitempty"`
	Tcpwaittodatarate                           int    `json:"tcpwaittodatarate,omitempty"`
	Tcpwaittosyn                                int    `json:"tcpwaittosyn,omitempty"`
	Tcpwaittosynrate                            int    `json:"tcpwaittosynrate,omitempty"`
	Tcpzombieactivehalfclosecltconnflushedrate  int    `json:"tcpzombieactivehalfclosecltconnflushedrate,omitempty"`
	Tcpzombieactivehalfclosesvrconnflushedrate  int    `json:"tcpzombieactivehalfclosesvrconnflushedrate,omitempty"`
	Tcpzombiecltconnflushedrate                 int    `json:"tcpzombiecltconnflushedrate,omitempty"`
	Tcpzombiehalfopencltconnflushedrate         int    `json:"tcpzombiehalfopencltconnflushedrate,omitempty"`
	Tcpzombiehalfopensvrconnflushedrate         int    `json:"tcpzombiehalfopensvrconnflushedrate,omitempty"`
	Tcpzombiepassivehalfclosecltconnflushedrate int    `json:"tcpzombiepassivehalfclosecltconnflushedrate,omitempty"`
	Tcpzombiepassivehalfclosesrvconnflushedrate int    `json:"tcpzombiepassivehalfclosesrvconnflushedrate,omitempty"`
	Tcpzombiesvrconnflushedrate                 int    `json:"tcpzombiesvrconnflushedrate,omitempty"`
}
