package cs

type Csvserverstats struct {
	Appfwpolicy                   interface{} `json:"appfwpolicy,omitempty"`
	Appqoepolicy                  interface{} `json:"appqoepolicy,omitempty"`
	Avgcltttlb                    int         `json:"avgcltttlb,omitempty"`
	Botpolicy                     interface{} `json:"botpolicy,omitempty"`
	Cachepolicy                   interface{} `json:"cachepolicy,omitempty"`
	Clearstats                    string      `json:"clearstats,omitempty"`
	Cltresponsetimeapdex          float64     `json:"cltresponsetimeapdex,omitempty"`
	Cmppolicy                     interface{} `json:"cmppolicy,omitempty"`
	Contentinspectionpolicy       interface{} `json:"contentinspectionpolicy,omitempty"`
	Curbackuppersistencesessions  int         `json:"curbackuppersistencesessions,omitempty"`
	Curclntconnections            int         `json:"curclntconnections,omitempty"`
	Curmptcpsessions              int         `json:"curmptcpsessions,omitempty"`
	Curpersistencesessions        int         `json:"curpersistencesessions,omitempty"`
	Cursrvrconnections            int         `json:"cursrvrconnections,omitempty"`
	Cursubflowconn                int         `json:"cursubflowconn,omitempty"`
	Deferredreq                   int         `json:"deferredreq,omitempty"`
	Deferredreqrate               int         `json:"deferredreqrate,omitempty"`
	Establishedconn               int         `json:"establishedconn,omitempty"`
	Frustratingttlbtransactions   int         `json:"frustratingttlbtransactions,omitempty"`
	Gslbvserver                   interface{} `json:"gslbvserver,omitempty"`
	Hitsrate                      int         `json:"hitsrate,omitempty"`
	Httpmaxhdrszpkts              int         `json:"httpmaxhdrszpkts,omitempty"`
	Invalidrequestresponse        int         `json:"invalidrequestresponse,omitempty"`
	Invalidrequestresponsedropped int         `json:"invalidrequestresponsedropped,omitempty"`
	Labelledconn                  int         `json:"labelledconn,omitempty"`
	Lbvserver                     interface{} `json:"lbvserver,omitempty"`
	Name                          string      `json:"name,omitempty"`
	Pktsrecvdrate                 int         `json:"pktsrecvdrate,omitempty"`
	Pktssentrate                  int         `json:"pktssentrate,omitempty"`
	Primaryipaddress              string      `json:"primaryipaddress,omitempty"`
	Primaryport                   int         `json:"primaryport,omitempty"`
	Pushlabel                     int         `json:"pushlabel,omitempty"`
	Requestbytesrate              int         `json:"requestbytesrate,omitempty"`
	Requestsrate                  int         `json:"requestsrate,omitempty"`
	Responderpolicy               interface{} `json:"responderpolicy,omitempty"`
	Responsebytesrate             int         `json:"responsebytesrate,omitempty"`
	Responsesrate                 int         `json:"responsesrate,omitempty"`
	Rewritepolicy                 interface{} `json:"rewritepolicy,omitempty"`
	Sothreshold                   int         `json:"sothreshold,omitempty"`
	Spilloverpolicy               interface{} `json:"spilloverpolicy,omitempty"`
	State                         string      `json:"state,omitempty"`
	Tcpmaxooopkts                 int         `json:"tcpmaxooopkts,omitempty"`
	Tmtrafficpolicy               interface{} `json:"tmtrafficpolicy,omitempty"`
	Toleratingttlbtransactions    int         `json:"toleratingttlbtransactions,omitempty"`
	Totalpktsrecvd                int         `json:"totalpktsrecvd,omitempty"`
	Totalpktssent                 int         `json:"totalpktssent,omitempty"`
	Totalrequestbytes             int         `json:"totalrequestbytes,omitempty"`
	Totalrequests                 int         `json:"totalrequests,omitempty"`
	Totalresponsebytes            int         `json:"totalresponsebytes,omitempty"`
	Totalresponses                int         `json:"totalresponses,omitempty"`
	Totcltttlbtransactions        int         `json:"totcltttlbtransactions,omitempty"`
	Tothits                       int         `json:"tothits,omitempty"`
	Totspillovers                 int         `json:"totspillovers,omitempty"`
	Totvserverdownbackuphits      int         `json:"totvserverdownbackuphits,omitempty"`
	Transformpolicy               interface{} `json:"transformpolicy,omitempty"`
	Type                          string      `json:"type,omitempty"`
	Vpnvserver                    interface{} `json:"vpnvserver,omitempty"`
}
