package lb

type Lbvserverstats struct {
	Actsvcs                          int         `json:"actsvcs,omitempty"`
	Appfwpolicy                      interface{} `json:"appfwpolicy,omitempty"`
	Appqoepolicy                     interface{} `json:"appqoepolicy,omitempty"`
	Avgcltttlb                       int         `json:"avgcltttlb,omitempty"`
	Botpolicy                        interface{} `json:"botpolicy,omitempty"`
	Cachepolicy                      interface{} `json:"cachepolicy,omitempty"`
	Clearstats                       string      `json:"clearstats,omitempty"`
	Cltresponsetimeapdex             float64     `json:"cltresponsetimeapdex,omitempty"`
	Cmppolicy                        interface{} `json:"cmppolicy,omitempty"`
	Contentinspectionpolicy          interface{} `json:"contentinspectionpolicy,omitempty"`
	Cpuusagepm                       int         `json:"cpuusagepm,omitempty"`
	Curbackuppersistencesessions     int         `json:"curbackuppersistencesessions,omitempty"`
	Curclntconnections               int         `json:"curclntconnections,omitempty"`
	Curmptcpsessions                 int         `json:"curmptcpsessions,omitempty"`
	Curpersistencesessions           int         `json:"curpersistencesessions,omitempty"`
	Cursrvrconnections               int         `json:"cursrvrconnections,omitempty"`
	Cursubflowconn                   int         `json:"cursubflowconn,omitempty"`
	Deferredreq                      int         `json:"deferredreq,omitempty"`
	Deferredreqrate                  int         `json:"deferredreqrate,omitempty"`
	Establishedconn                  int         `json:"establishedconn,omitempty"`
	Frustratingttlbtransactions      int         `json:"frustratingttlbtransactions,omitempty"`
	H2requestsrate                   int         `json:"h2requestsrate,omitempty"`
	H2responsesrate                  int         `json:"h2responsesrate,omitempty"`
	Hitsrate                         int         `json:"hitsrate,omitempty"`
	Httpmaxhdrszpkts                 int         `json:"httpmaxhdrszpkts,omitempty"`
	Inactsvcs                        int         `json:"inactsvcs,omitempty"`
	Invalidrequestresponse           int         `json:"invalidrequestresponse,omitempty"`
	Invalidrequestresponsedropped    int         `json:"invalidrequestresponsedropped,omitempty"`
	Labelledconn                     int         `json:"labelledconn,omitempty"`
	Name                             string      `json:"name,omitempty"`
	Pktsrecvdrate                    int         `json:"pktsrecvdrate,omitempty"`
	Pktssentrate                     int         `json:"pktssentrate,omitempty"`
	Pqpolicy                         interface{} `json:"pqpolicy,omitempty"`
	Primaryipaddress                 string      `json:"primaryipaddress,omitempty"`
	Primaryport                      int         `json:"primaryport,omitempty"`
	Pushlabel                        int         `json:"pushlabel,omitempty"`
	Reqretrycount                    int         `json:"reqretrycount,omitempty"`
	Reqretrycountexceeded            int         `json:"reqretrycountexceeded,omitempty"`
	Requestbytesrate                 int         `json:"requestbytesrate,omitempty"`
	Requestsrate                     int         `json:"requestsrate,omitempty"`
	Responderpolicy                  interface{} `json:"responderpolicy,omitempty"`
	Responsebytesrate                int         `json:"responsebytesrate,omitempty"`
	Responsesrate                    int         `json:"responsesrate,omitempty"`
	Rewritepolicy                    interface{} `json:"rewritepolicy,omitempty"`
	Scpolicy                         interface{} `json:"scpolicy,omitempty"`
	Service                          interface{} `json:"service,omitempty"`
	Servicegroup                     interface{} `json:"servicegroup,omitempty"`
	Sortby                           string      `json:"sortby,omitempty"`
	Sortorder                        string      `json:"sortorder,omitempty"`
	Sothreshold                      int         `json:"sothreshold,omitempty"`
	Spilloverpolicy                  interface{} `json:"spilloverpolicy,omitempty"`
	State                            string      `json:"state,omitempty"`
	Surgecount                       int         `json:"surgecount,omitempty"`
	Svcsurgecount                    int         `json:"svcsurgecount,omitempty"`
	Svrbusyerrrate                   int         `json:"svrbusyerrrate,omitempty"`
	Tcpmaxooopkts                    int         `json:"tcpmaxooopkts,omitempty"`
	Tmtrafficpolicy                  interface{} `json:"tmtrafficpolicy,omitempty"`
	Toleratingttlbtransactions       int         `json:"toleratingttlbtransactions,omitempty"`
	Totalconnreassemblyqueue75       int         `json:"totalconnreassemblyqueue75,omitempty"`
	Totalconnreassemblyqueueflush    int         `json:"totalconnreassemblyqueueflush,omitempty"`
	Totalh2requests                  int         `json:"totalh2requests,omitempty"`
	Totalh2responses                 int         `json:"totalh2responses,omitempty"`
	Totalpktsrecvd                   int         `json:"totalpktsrecvd,omitempty"`
	Totalpktssent                    int         `json:"totalpktssent,omitempty"`
	Totalrequestbytes                int         `json:"totalrequestbytes,omitempty"`
	Totalrequests                    int         `json:"totalrequests,omitempty"`
	Totalresponsebytes               int         `json:"totalresponsebytes,omitempty"`
	Totalresponses                   int         `json:"totalresponses,omitempty"`
	Totalsvrbusyerr                  int         `json:"totalsvrbusyerr,omitempty"`
	Totcltttlbtransactions           int         `json:"totcltttlbtransactions,omitempty"`
	Tothits                          int         `json:"tothits,omitempty"`
	Totspillovers                    int         `json:"totspillovers,omitempty"`
	Totvserverdownbackuphits         int         `json:"totvserverdownbackuphits,omitempty"`
	Transformpolicy                  interface{} `json:"transformpolicy,omitempty"`
	Type                             string      `json:"type,omitempty"`
	Videooptimizationdetectionpolicy interface{} `json:"videooptimizationdetectionpolicy,omitempty"`
	Videooptimizationpacingpolicy    interface{} `json:"videooptimizationpacingpolicy,omitempty"`
	Vslbhealth                       int         `json:"vslbhealth,omitempty"`
	Vsvrsurgecount                   int         `json:"vsvrsurgecount,omitempty"`
}
