package appqoe

type Appqoestats struct {
	Clearstats            string `json:"clearstats,omitempty"`
	Doshfaultycookiesrate int    `json:"doshfaultycookiesrate,omitempty"`
	Doshvalidcookiesrate  int    `json:"doshvalidcookiesrate,omitempty"`
	Dosqfaultycookiesrate int    `json:"dosqfaultycookiesrate,omitempty"`
	Dosqvalidcookiesrate  int    `json:"dosqvalidcookiesrate,omitempty"`
	Dostrigrate           int    `json:"dostrigrate,omitempty"`
	Faultycookiesrate     int    `json:"faultycookiesrate,omitempty"`
	Getinmemrsprate       int    `json:"getinmemrsprate,omitempty"`
	Highprireqrate        int    `json:"highprireqrate,omitempty"`
	Inmemrsprate          int    `json:"inmemrsprate,omitempty"`
	Lowestprireqrate      int    `json:"lowestprireqrate,omitempty"`
	Lowprireqrate         int    `json:"lowprireqrate,omitempty"`
	Mediumprireqrate      int    `json:"mediumprireqrate,omitempty"`
	Onhfaultycookiesrate  int    `json:"onhfaultycookiesrate,omitempty"`
	Onhvalidcookiesrate   int    `json:"onhvalidcookiesrate,omitempty"`
	Postinmemrspbytesrate int    `json:"postinmemrspbytesrate,omitempty"`
	Postinmemrsprate      int    `json:"postinmemrsprate,omitempty"`
	Priembedlinksrate     int    `json:"priembedlinksrate,omitempty"`
	Priqfaultycookiesrate int    `json:"priqfaultycookiesrate,omitempty"`
	Priqvalidcookiesrate  int    `json:"priqvalidcookiesrate,omitempty"`
	Sessreqrate           int    `json:"sessreqrate,omitempty"`
	Sidfaultycookiesrate  int    `json:"sidfaultycookiesrate,omitempty"`
	Sidvalidcookiesrate   int    `json:"sidvalidcookiesrate,omitempty"`
	Tcntreqrate           int    `json:"tcntreqrate,omitempty"`
	Totaltcntreq          int    `json:"totaltcntreq,omitempty"`
	Totaltsvrsubfailed    int    `json:"totaltsvrsubfailed,omitempty"`
	Totdoshfaultycookies  int    `json:"totdoshfaultycookies,omitempty"`
	Totdoshvalidcookies   int    `json:"totdoshvalidcookies,omitempty"`
	Totdosqfaultycookies  int    `json:"totdosqfaultycookies,omitempty"`
	Totdosqvalidcookies   int    `json:"totdosqvalidcookies,omitempty"`
	Totdostrig            int    `json:"totdostrig,omitempty"`
	Totfaultycookies      int    `json:"totfaultycookies,omitempty"`
	Totgetinmemrsp        int    `json:"totgetinmemrsp,omitempty"`
	Tothighprireq         int    `json:"tothighprireq,omitempty"`
	Totinmemrsp           int    `json:"totinmemrsp,omitempty"`
	Totlowestprireq       int    `json:"totlowestprireq,omitempty"`
	Totlowprireq          int    `json:"totlowprireq,omitempty"`
	Totmediumprireq       int    `json:"totmediumprireq,omitempty"`
	Totonhfaultycookies   int    `json:"totonhfaultycookies,omitempty"`
	Totonhvalidcookies    int    `json:"totonhvalidcookies,omitempty"`
	Totpostinmemrsp       int    `json:"totpostinmemrsp,omitempty"`
	Totpostinmemrspbytes  int    `json:"totpostinmemrspbytes,omitempty"`
	Totpriembedlinks      int    `json:"totpriembedlinks,omitempty"`
	Totpriqfaultycookies  int    `json:"totpriqfaultycookies,omitempty"`
	Totpriqvalidcookies   int    `json:"totpriqvalidcookies,omitempty"`
	Totsessreq            int    `json:"totsessreq,omitempty"`
	Totsidfaultycookies   int    `json:"totsidfaultycookies,omitempty"`
	Totsidvalidcookies    int    `json:"totsidvalidcookies,omitempty"`
	Totvalidcookies       int    `json:"totvalidcookies,omitempty"`
	Tsvrsubfailedrate     int    `json:"tsvrsubfailedrate,omitempty"`
	Validcookiesrate      int    `json:"validcookiesrate,omitempty"`
}
