package system

type Systembwstats struct {
	Clearstats             string `json:"clearstats,omitempty"`
	Httpclterrstray        int    `json:"httpclterrstray,omitempty"`
	Httpclterrstrayrate    int    `json:"httpclterrstrayrate,omitempty"`
	Httpcltpoolinactive    int    `json:"httpcltpoolinactive,omitempty"`
	Httpcltpooloutactive   int    `json:"httpcltpooloutactive,omitempty"`
	Httpcltttfp0           int    `json:"httpcltttfp_0,omitempty"`
	Httpcltttfp0rate       int    `json:"httpcltttfp_0rate,omitempty"`
	Httpcltttfp1           int    `json:"httpcltttfp_1,omitempty"`
	Httpcltttfp1rate       int    `json:"httpcltttfp_1rate,omitempty"`
	Httpcltttfp2           int    `json:"httpcltttfp_2,omitempty"`
	Httpcltttfp2rate       int    `json:"httpcltttfp_2rate,omitempty"`
	Httpcltttfp3           int    `json:"httpcltttfp_3,omitempty"`
	Httpcltttfp3rate       int    `json:"httpcltttfp_3rate,omitempty"`
	Httpcltttfp4           int    `json:"httpcltttfp_4,omitempty"`
	Httpcltttfp4rate       int    `json:"httpcltttfp_4rate,omitempty"`
	Httpcltttfp5           int    `json:"httpcltttfp_5,omitempty"`
	Httpcltttfp5rate       int    `json:"httpcltttfp_5rate,omitempty"`
	Httpcltttfp6           int    `json:"httpcltttfp_6,omitempty"`
	Httpcltttfp6rate       int    `json:"httpcltttfp_6rate,omitempty"`
	Httpcltttfp7           int    `json:"httpcltttfp_7,omitempty"`
	Httpcltttfp7rate       int    `json:"httpcltttfp_7rate,omitempty"`
	Httpcltttfphwm         int    `json:"httpcltttfphwm,omitempty"`
	Httpcltttfphwmrate     int    `json:"httpcltttfphwmrate,omitempty"`
	Httpcltttfplwm         int    `json:"httpcltttfplwm,omitempty"`
	Httpcltttfplwmrate     int    `json:"httpcltttfplwmrate,omitempty"`
	Httpcltttfpmax         int    `json:"httpcltttfpmax,omitempty"`
	Httpcltttlp0           int    `json:"httpcltttlp_0,omitempty"`
	Httpcltttlp0rate       int    `json:"httpcltttlp_0rate,omitempty"`
	Httpcltttlp1           int    `json:"httpcltttlp_1,omitempty"`
	Httpcltttlp1rate       int    `json:"httpcltttlp_1rate,omitempty"`
	Httpcltttlp2           int    `json:"httpcltttlp_2,omitempty"`
	Httpcltttlp2rate       int    `json:"httpcltttlp_2rate,omitempty"`
	Httpcltttlp3           int    `json:"httpcltttlp_3,omitempty"`
	Httpcltttlp3rate       int    `json:"httpcltttlp_3rate,omitempty"`
	Httpcltttlp4           int    `json:"httpcltttlp_4,omitempty"`
	Httpcltttlp4rate       int    `json:"httpcltttlp_4rate,omitempty"`
	Httpcltttlp5           int    `json:"httpcltttlp_5,omitempty"`
	Httpcltttlp5rate       int    `json:"httpcltttlp_5rate,omitempty"`
	Httpcltttlp6           int    `json:"httpcltttlp_6,omitempty"`
	Httpcltttlp6rate       int    `json:"httpcltttlp_6rate,omitempty"`
	Httpcltttlp7           int    `json:"httpcltttlp_7,omitempty"`
	Httpcltttlp7rate       int    `json:"httpcltttlp_7rate,omitempty"`
	Httpcltttlphwm         int    `json:"httpcltttlphwm,omitempty"`
	Httpcltttlphwmrate     int    `json:"httpcltttlphwmrate,omitempty"`
	Httpcltttlplwm         int    `json:"httpcltttlplwm,omitempty"`
	Httpcltttlplwmrate     int    `json:"httpcltttlplwmrate,omitempty"`
	Httpcltttlpmax         int    `json:"httpcltttlpmax,omitempty"`
	Httpsvr200okresp       int    `json:"httpsvr200okresp,omitempty"`
	Httpsvr200okresprate   int    `json:"httpsvr200okresprate,omitempty"`
	Httpsvr404notfound     int    `json:"httpsvr404notfound,omitempty"`
	Httpsvr404notfoundrate int    `json:"httpsvr404notfoundrate,omitempty"`
}
