package cmp

type Cmpstats struct {
	Clearstats                     string  `json:"clearstats,omitempty"`
	Comphttpbandwidthsaving        float64 `json:"comphttpbandwidthsaving,omitempty"`
	Compratio                      float64 `json:"compratio,omitempty"`
	Comprequestsrate               int     `json:"comprequestsrate,omitempty"`
	Comprxbytesrate                int     `json:"comprxbytesrate,omitempty"`
	Comprxpacketsrate              int     `json:"comprxpacketsrate,omitempty"`
	Comptcpbandwidthsaving         float64 `json:"comptcpbandwidthsaving,omitempty"`
	Comptcpeoirate                 int     `json:"comptcpeoirate,omitempty"`
	Comptcppushrate                int     `json:"comptcppushrate,omitempty"`
	Comptcpquantumrate             int     `json:"comptcpquantumrate,omitempty"`
	Comptcpratio                   float64 `json:"comptcpratio,omitempty"`
	Comptcprxbytesrate             int     `json:"comptcprxbytesrate,omitempty"`
	Comptcprxpacketsrate           int     `json:"comptcprxpacketsrate,omitempty"`
	Comptcptimerrate               int     `json:"comptcptimerrate,omitempty"`
	Comptcptotaleoi                int     `json:"comptcptotaleoi,omitempty"`
	Comptcptotalpush               int     `json:"comptcptotalpush,omitempty"`
	Comptcptotalquantum            int     `json:"comptcptotalquantum,omitempty"`
	Comptcptotalrxbytes            int     `json:"comptcptotalrxbytes,omitempty"`
	Comptcptotalrxpackets          int     `json:"comptcptotalrxpackets,omitempty"`
	Comptcptotaltimer              int     `json:"comptcptotaltimer,omitempty"`
	Comptcptotaltxbytes            int     `json:"comptcptotaltxbytes,omitempty"`
	Comptcptotaltxpackets          int     `json:"comptcptotaltxpackets,omitempty"`
	Comptcptxbytesrate             int     `json:"comptcptxbytesrate,omitempty"`
	Comptcptxpacketsrate           int     `json:"comptcptxpacketsrate,omitempty"`
	Comptotaldatacompressionratio  float64 `json:"comptotaldatacompressionratio,omitempty"`
	Comptotalrequests              int     `json:"comptotalrequests,omitempty"`
	Comptotalrxbytes               int     `json:"comptotalrxbytes,omitempty"`
	Comptotalrxpackets             int     `json:"comptotalrxpackets,omitempty"`
	Comptotaltxbytes               int     `json:"comptotaltxbytes,omitempty"`
	Comptotaltxpackets             int     `json:"comptotaltxpackets,omitempty"`
	Comptxbytesrate                int     `json:"comptxbytesrate,omitempty"`
	Comptxpacketsrate              int     `json:"comptxpacketsrate,omitempty"`
	Decomptcpbandwidthsaving       float64 `json:"decomptcpbandwidthsaving,omitempty"`
	Decomptcperrdata               int     `json:"decomptcperrdata,omitempty"`
	Decomptcperrdatarate           int     `json:"decomptcperrdatarate,omitempty"`
	Decomptcperrlessdata           int     `json:"decomptcperrlessdata,omitempty"`
	Decomptcperrlessdatarate       int     `json:"decomptcperrlessdatarate,omitempty"`
	Decomptcperrmemory             int     `json:"decomptcperrmemory,omitempty"`
	Decomptcperrmemoryrate         int     `json:"decomptcperrmemoryrate,omitempty"`
	Decomptcperrmoredata           int     `json:"decomptcperrmoredata,omitempty"`
	Decomptcperrmoredatarate       int     `json:"decomptcperrmoredatarate,omitempty"`
	Decomptcperrunknown            int     `json:"decomptcperrunknown,omitempty"`
	Decomptcperrunknownrate        int     `json:"decomptcperrunknownrate,omitempty"`
	Decomptcpratio                 float64 `json:"decomptcpratio,omitempty"`
	Decomptcprxbytes               int     `json:"decomptcprxbytes,omitempty"`
	Decomptcprxbytesrate           int     `json:"decomptcprxbytesrate,omitempty"`
	Decomptcprxpackets             int     `json:"decomptcprxpackets,omitempty"`
	Decomptcprxpacketsrate         int     `json:"decomptcprxpacketsrate,omitempty"`
	Decomptcptxbytes               int     `json:"decomptcptxbytes,omitempty"`
	Decomptcptxbytesrate           int     `json:"decomptcptxbytesrate,omitempty"`
	Decomptcptxpackets             int     `json:"decomptcptxpackets,omitempty"`
	Decomptcptxpacketsrate         int     `json:"decomptcptxpacketsrate,omitempty"`
	Delbwsaving                    float64 `json:"delbwsaving,omitempty"`
	Delcmpratio                    float64 `json:"delcmpratio,omitempty"`
	Delcompbaseserved              int     `json:"delcompbaseserved,omitempty"`
	Delcompbaseservedrate          int     `json:"delcompbaseservedrate,omitempty"`
	Delcompbasetcptxbytes          int     `json:"delcompbasetcptxbytes,omitempty"`
	Delcompbasetcptxbytesrate      int     `json:"delcompbasetcptxbytesrate,omitempty"`
	Delcompdone                    int     `json:"delcompdone,omitempty"`
	Delcompdonerate                int     `json:"delcompdonerate,omitempty"`
	Delcomperrbfilewhdrfailed      int     `json:"delcomperrbfilewhdrfailed,omitempty"`
	Delcomperrbfilewhdrfailedrate  int     `json:"delcomperrbfilewhdrfailedrate,omitempty"`
	Delcomperrbypassed             int     `json:"delcomperrbypassed,omitempty"`
	Delcomperrbypassedrate         int     `json:"delcomperrbypassedrate,omitempty"`
	Delcomperrnostoremiss          int     `json:"delcomperrnostoremiss,omitempty"`
	Delcomperrnostoremissrate      int     `json:"delcomperrnostoremissrate,omitempty"`
	Delcomperrreqinfoallocfail     int     `json:"delcomperrreqinfoallocfail,omitempty"`
	Delcomperrreqinfoallocfailrate int     `json:"delcomperrreqinfoallocfailrate,omitempty"`
	Delcomperrreqinfotoobig        int     `json:"delcomperrreqinfotoobig,omitempty"`
	Delcomperrreqinfotoobigrate    int     `json:"delcomperrreqinfotoobigrate,omitempty"`
	Delcomperrsessallocfail        int     `json:"delcomperrsessallocfail,omitempty"`
	Delcomperrsessallocfailrate    int     `json:"delcomperrsessallocfailrate,omitempty"`
	Delcompfirstaccess             int     `json:"delcompfirstaccess,omitempty"`
	Delcompfirstaccessrate         int     `json:"delcompfirstaccessrate,omitempty"`
	Delcomprequestsrate            int     `json:"delcomprequestsrate,omitempty"`
	Delcomptcprxbytes              int     `json:"delcomptcprxbytes,omitempty"`
	Delcomptcprxbytesrate          int     `json:"delcomptcprxbytesrate,omitempty"`
	Delcomptcprxpackets            int     `json:"delcomptcprxpackets,omitempty"`
	Delcomptcprxpacketsrate        int     `json:"delcomptcprxpacketsrate,omitempty"`
	Delcomptcptxbytes              int     `json:"delcomptcptxbytes,omitempty"`
	Delcomptcptxbytesrate          int     `json:"delcomptcptxbytesrate,omitempty"`
	Delcomptcptxpackets            int     `json:"delcomptcptxpackets,omitempty"`
	Delcomptcptxpacketsrate        int     `json:"delcomptcptxpacketsrate,omitempty"`
	Delcomptotalrequests           int     `json:"delcomptotalrequests,omitempty"`
}
