package feo

type Feostats struct {
	Cacheextendedrate       int    `json:"cacheextendedrate,omitempty"`
	Clearstats              string `json:"clearstats,omitempty"`
	Csscombinedrate         int    `json:"csscombinedrate,omitempty"`
	Cssminrate              int    `json:"cssminrate,omitempty"`
	Cssmovedrate            int    `json:"cssmovedrate,omitempty"`
	Datasavingsrate         int    `json:"datasavingsrate,omitempty"`
	Gifstopngrate           int    `json:"gifstopngrate,omitempty"`
	Htmlcommentsremoved     int    `json:"htmlcommentsremoved,omitempty"`
	Htmlcommentsremovedrate int    `json:"htmlcommentsremovedrate,omitempty"`
	Imgsdomainshardedrate   int    `json:"imgsdomainshardedrate,omitempty"`
	Imgsinlinedincssrate    int    `json:"imgsinlinedincssrate,omitempty"`
	Imgslazyloadedrate      int    `json:"imgslazyloadedrate,omitempty"`
	Imgsresizedrate         int    `json:"imgsresizedrate,omitempty"`
	Imgstojxrrate           int    `json:"imgstojxrrate,omitempty"`
	Imgstowebprate          int    `json:"imgstowebprate,omitempty"`
	Importtolinkrate        int    `json:"importtolinkrate,omitempty"`
	Inlinedcssrate          int    `json:"inlinedcssrate,omitempty"`
	Inlinedimgsrate         int    `json:"inlinedimgsrate,omitempty"`
	Inlinedjsrate           int    `json:"inlinedjsrate,omitempty"`
	Jpegsoptimizedrate      int    `json:"jpegsoptimizedrate,omitempty"`
	Jsminrate               int    `json:"jsminrate,omitempty"`
	Jsmovedrate             int    `json:"jsmovedrate,omitempty"`
	Optcacheobjects         int    `json:"optcacheobjects,omitempty"`
	Optcacheobjectsrate     int    `json:"optcacheobjectsrate,omitempty"`
	Origcacheobjects        int    `json:"origcacheobjects,omitempty"`
	Origcacheobjectsrate    int    `json:"origcacheobjectsrate,omitempty"`
	Totalcacheextended      int    `json:"totalcacheextended,omitempty"`
	Totalcsscombined        int    `json:"totalcsscombined,omitempty"`
	Totalcssmin             int    `json:"totalcssmin,omitempty"`
	Totalcssmoved           int    `json:"totalcssmoved,omitempty"`
	Totaldatasavings        int    `json:"totaldatasavings,omitempty"`
	Totalgifstopng          int    `json:"totalgifstopng,omitempty"`
	Totalimgsdomainsharded  int    `json:"totalimgsdomainsharded,omitempty"`
	Totalimgsinlinedincss   int    `json:"totalimgsinlinedincss,omitempty"`
	Totalimgslazyloaded     int    `json:"totalimgslazyloaded,omitempty"`
	Totalimgsresized        int    `json:"totalimgsresized,omitempty"`
	Totalimgstojxr          int    `json:"totalimgstojxr,omitempty"`
	Totalimgstowebp         int    `json:"totalimgstowebp,omitempty"`
	Totalimporttolink       int    `json:"totalimporttolink,omitempty"`
	Totalinlinedcss         int    `json:"totalinlinedcss,omitempty"`
	Totalinlinedimgs        int    `json:"totalinlinedimgs,omitempty"`
	Totalinlinedjs          int    `json:"totalinlinedjs,omitempty"`
	Totaljpegsoptimized     int    `json:"totaljpegsoptimized,omitempty"`
	Totaljsmin              int    `json:"totaljsmin,omitempty"`
	Totaljsmoved            int    `json:"totaljsmoved,omitempty"`
	Toturireplaced          int    `json:"toturireplaced,omitempty"`
	Urireplacedrate         int    `json:"urireplacedrate,omitempty"`
}
