package ns

type Nsstats struct {
	Appfirewallaborts                int     `json:"appfirewallaborts,omitempty"`
	Appfirewallabortsrate            int     `json:"appfirewallabortsrate,omitempty"`
	Appfirewallredirects             int     `json:"appfirewallredirects,omitempty"`
	Appfirewallredirectsrate         int     `json:"appfirewallredirectsrate,omitempty"`
	Appfirewallrequests              int     `json:"appfirewallrequests,omitempty"`
	Appfirewallrequestsrate          int     `json:"appfirewallrequestsrate,omitempty"`
	Appfirewallresponses             int     `json:"appfirewallresponses,omitempty"`
	Appfirewallresponsesrate         int     `json:"appfirewallresponsesrate,omitempty"`
	Cache64maxmemorykb               int     `json:"cache64maxmemorykb,omitempty"`
	Cachehitsrate                    int     `json:"cachehitsrate,omitempty"`
	Cachemaxmemoryactivekb           int     `json:"cachemaxmemoryactivekb,omitempty"`
	Cachemaxmemorykb                 int     `json:"cachemaxmemorykb,omitempty"`
	Cachemissesrate                  int     `json:"cachemissesrate,omitempty"`
	Cachepercentoriginbandwidthsaved int     `json:"cachepercentoriginbandwidthsaved,omitempty"`
	Cachetothits                     int     `json:"cachetothits,omitempty"`
	Cachetotmisses                   int     `json:"cachetotmisses,omitempty"`
	Cacheutilizedmemorykb            int     `json:"cacheutilizedmemorykb,omitempty"`
	Clearstats                       string  `json:"clearstats,omitempty"`
	Compratio                        float64 `json:"compratio,omitempty"`
	Comptotaldatacompressionratio    float64 `json:"comptotaldatacompressionratio,omitempty"`
	Cpuusage                         int     `json:"cpuusage,omitempty"`
	Cpuusagepcnt                     float64 `json:"cpuusagepcnt,omitempty"`
	Delcmpratio                      float64 `json:"delcmpratio,omitempty"`
	Disk0avail                       int     `json:"disk0avail,omitempty"`
	Disk0perusage                    int     `json:"disk0perusage,omitempty"`
	Disk1avail                       int     `json:"disk1avail,omitempty"`
	Disk1perusage                    int     `json:"disk1perusage,omitempty"`
	Hacurmasterstate                 string  `json:"hacurmasterstate,omitempty"`
	Hacurstate                       string  `json:"hacurstate,omitempty"`
	Httprequestsrate                 int     `json:"httprequestsrate,omitempty"`
	Httpresponsesrate                int     `json:"httpresponsesrate,omitempty"`
	Httprxrequestbytesrate           int     `json:"httprxrequestbytesrate,omitempty"`
	Httprxresponsebytesrate          int     `json:"httprxresponsebytesrate,omitempty"`
	Httptotrequests                  int     `json:"httptotrequests,omitempty"`
	Httptotresponses                 int     `json:"httptotresponses,omitempty"`
	Httptotrxrequestbytes            int     `json:"httptotrxrequestbytes,omitempty"`
	Httptotrxresponsebytes           int     `json:"httptotrxresponsebytes,omitempty"`
	Memusagepcnt                     float64 `json:"memusagepcnt,omitempty"`
	Memuseinmb                       int     `json:"memuseinmb,omitempty"`
	Mgmtcpuusagepcnt                 float64 `json:"mgmtcpuusagepcnt,omitempty"`
	Misccounter0                     int     `json:"misccounter0,omitempty"`
	Misccounter1                     int     `json:"misccounter1,omitempty"`
	Numcpus                          int     `json:"numcpus,omitempty"`
	Pktcpuusagepcnt                  float64 `json:"pktcpuusagepcnt,omitempty"`
	Rescpuusage                      int     `json:"rescpuusage,omitempty"`
	Rescpuusagepcnt                  float64 `json:"rescpuusagepcnt,omitempty"`
	Resmemusage                      int     `json:"resmemusage,omitempty"`
	Rxmbitsrate                      int     `json:"rxmbitsrate,omitempty"`
	Sslcards                         int     `json:"sslcards,omitempty"`
	Sslnumcardsup                    int     `json:"sslnumcardsup,omitempty"`
	Sslsessionhitsrate               int     `json:"sslsessionhitsrate,omitempty"`
	Ssltotsessionhits                int     `json:"ssltotsessionhits,omitempty"`
	Ssltottransactions               int     `json:"ssltottransactions,omitempty"`
	Ssltransactionsrate              int     `json:"ssltransactionsrate,omitempty"`
	Starttime                        string  `json:"starttime,omitempty"`
	Starttimelocal                   string  `json:"starttimelocal,omitempty"`
	Tcpcurclientconn                 int     `json:"tcpcurclientconn,omitempty"`
	Tcpcurclientconnestablished      int     `json:"tcpcurclientconnestablished,omitempty"`
	Tcpcurserverconn                 int     `json:"tcpcurserverconn,omitempty"`
	Tcpcurserverconnestablished      int     `json:"tcpcurserverconnestablished,omitempty"`
	Totrxmbits                       int     `json:"totrxmbits,omitempty"`
	Tottxmbits                       int     `json:"tottxmbits,omitempty"`
	Transtime                        string  `json:"transtime,omitempty"`
	Txmbitsrate                      int     `json:"txmbitsrate,omitempty"`
}
