package vpn

type Vpnstats struct {
	Cfghtmlserved                 int    `json:"cfghtmlserved,omitempty"`
	Cfghtmlservedrate             int    `json:"cfghtmlservedrate,omitempty"`
	Clearstats                    string `json:"clearstats,omitempty"`
	Cpsconnfailure                int    `json:"cpsconnfailure,omitempty"`
	Cpsconnfailurerate            int    `json:"cpsconnfailurerate,omitempty"`
	Cpsconnsuccess                int    `json:"cpsconnsuccess,omitempty"`
	Cpsconnsuccessrate            int    `json:"cpsconnsuccessrate,omitempty"`
	Csconnsuccrate                int    `json:"csconnsuccrate,omitempty"`
	Csgptktvalidatenotstarted     int    `json:"csgptktvalidatenotstarted,omitempty"`
	Csgptktvalidatenotstartedrate int    `json:"csgptktvalidatenotstartedrate,omitempty"`
	Csgrtktvalidatenotstarted     int    `json:"csgrtktvalidatenotstarted,omitempty"`
	Csgrtktvalidatenotstartedrate int    `json:"csgrtktvalidatenotstartedrate,omitempty"`
	Cshttpprobehit                int    `json:"cshttpprobehit,omitempty"`
	Cshttpprobehitrate            int    `json:"cshttpprobehitrate,omitempty"`
	Csnonhttpprobehit             int    `json:"csnonhttpprobehit,omitempty"`
	Csnonhttpprobehitrate         int    `json:"csnonhttpprobehitrate,omitempty"`
	Csrequesthit                  int    `json:"csrequesthit,omitempty"`
	Csrequesthitrate              int    `json:"csrequesthitrate,omitempty"`
	Dnsreqhit                     int    `json:"dnsreqhit,omitempty"`
	Dnsreqhitrate                 int    `json:"dnsreqhitrate,omitempty"`
	Fsrequestrate                 int    `json:"fsrequestrate,omitempty"`
	Icalicensefailure             int    `json:"icalicensefailure,omitempty"`
	Icalicensefailurerate         int    `json:"icalicensefailurerate,omitempty"`
	Iipdisabledmipdisabled        int    `json:"iipdisabledmipdisabled,omitempty"`
	Iipdisabledmipdisabledrate    int    `json:"iipdisabledmipdisabledrate,omitempty"`
	Iipdisabledmipused            int    `json:"iipdisabledmipused,omitempty"`
	Iipdisabledmipusedrate        int    `json:"iipdisabledmipusedrate,omitempty"`
	Iipfailedmipdisabled          int    `json:"iipfailedmipdisabled,omitempty"`
	Iipfailedmipdisabledrate      int    `json:"iipfailedmipdisabledrate,omitempty"`
	Iipfailedmipused              int    `json:"iipfailedmipused,omitempty"`
	Iipfailedmipusedrate          int    `json:"iipfailedmipusedrate,omitempty"`
	Iipspillovermipused           int    `json:"iipspillovermipused,omitempty"`
	Iipspillovermipusedrate       int    `json:"iipspillovermipusedrate,omitempty"`
	Indexhtmlhit                  int    `json:"indexhtmlhit,omitempty"`
	Indexhtmlnoserved             int    `json:"indexhtmlnoserved,omitempty"`
	Socksclienterror              int    `json:"socksclienterror,omitempty"`
	Socksclienterrorrate          int    `json:"socksclienterrorrate,omitempty"`
	Socksconnreqrcvd              int    `json:"socksconnreqrcvd,omitempty"`
	Socksconnreqrcvdrate          int    `json:"socksconnreqrcvdrate,omitempty"`
	Socksconnreqsent              int    `json:"socksconnreqsent,omitempty"`
	Socksconnreqsentrate          int    `json:"socksconnreqsentrate,omitempty"`
	Socksconnresprcvd             int    `json:"socksconnresprcvd,omitempty"`
	Socksconnresprcvdrate         int    `json:"socksconnresprcvdrate,omitempty"`
	Socksconnrespsent             int    `json:"socksconnrespsent,omitempty"`
	Socksconnrespsentrate         int    `json:"socksconnrespsentrate,omitempty"`
	Socksmethreqrcvd              int    `json:"socksmethreqrcvd,omitempty"`
	Socksmethreqrcvdrate          int    `json:"socksmethreqrcvdrate,omitempty"`
	Socksmethreqsent              int    `json:"socksmethreqsent,omitempty"`
	Socksmethreqsentrate          int    `json:"socksmethreqsentrate,omitempty"`
	Socksmethresprcvd             int    `json:"socksmethresprcvd,omitempty"`
	Socksmethresprcvdrate         int    `json:"socksmethresprcvdrate,omitempty"`
	Socksmethrespsent             int    `json:"socksmethrespsent,omitempty"`
	Socksmethrespsentrate         int    `json:"socksmethrespsentrate,omitempty"`
	Socksservererror              int    `json:"socksservererror,omitempty"`
	Socksservererrorrate          int    `json:"socksservererrorrate,omitempty"`
	Staconnfailure                int    `json:"staconnfailure,omitempty"`
	Staconnfailurerate            int    `json:"staconnfailurerate,omitempty"`
	Staconnsuccess                int    `json:"staconnsuccess,omitempty"`
	Staconnsuccessrate            int    `json:"staconnsuccessrate,omitempty"`
	Stamonfail                    int    `json:"stamonfail,omitempty"`
	Stamonfailrate                int    `json:"stamonfailrate,omitempty"`
	Stamonrcvd                    int    `json:"stamonrcvd,omitempty"`
	Stamonrcvdrate                int    `json:"stamonrcvdrate,omitempty"`
	Stamonsent                    int    `json:"stamonsent,omitempty"`
	Stamonsentrate                int    `json:"stamonsentrate,omitempty"`
	Stamonsucc                    int    `json:"stamonsucc,omitempty"`
	Stamonsuccrate                int    `json:"stamonsuccrate,omitempty"`
	Starequestsent                int    `json:"starequestsent,omitempty"`
	Starequestsentrate            int    `json:"starequestsentrate,omitempty"`
	Staresponserecvd              int    `json:"staresponserecvd,omitempty"`
	Staresponserecvdrate          int    `json:"staresponserecvdrate,omitempty"`
	Totalcsconnsucc               int    `json:"totalcsconnsucc,omitempty"`
	Totalfsrequest                int    `json:"totalfsrequest,omitempty"`
	Vpnlicensefail                int    `json:"vpnlicensefail,omitempty"`
	Winsrequesthit                int    `json:"winsrequesthit,omitempty"`
	Winsrequesthitrate            int    `json:"winsrequesthitrate,omitempty"`
}
