package network

type Interfacestats struct {
	Clearstats               string `json:"clearstats,omitempty"`
	Curintfstate             string `json:"curintfstate,omitempty"`
	Curlinkdowntime          string `json:"curlinkdowntime,omitempty"`
	Curlinkstate             string `json:"curlinkstate,omitempty"`
	Curlinkuptime            string `json:"curlinkuptime,omitempty"`
	Errdroppedrxpkts         int    `json:"errdroppedrxpkts,omitempty"`
	Errdroppedrxpktsrate     int    `json:"errdroppedrxpktsrate,omitempty"`
	Errdroppedtxpkts         int    `json:"errdroppedtxpkts,omitempty"`
	Errdroppedtxpktsrate     int    `json:"errdroppedtxpktsrate,omitempty"`
	Errifindiscards          int    `json:"errifindiscards,omitempty"`
	Errifindiscardsrate      int    `json:"errifindiscardsrate,omitempty"`
	Errlinkhangs             int    `json:"errlinkhangs,omitempty"`
	Errnicmuted              int    `json:"errnicmuted,omitempty"`
	Errpktrx                 int    `json:"errpktrx,omitempty"`
	Errpktrxrate             int    `json:"errpktrxrate,omitempty"`
	Errpkttx                 int    `json:"errpkttx,omitempty"`
	Errpkttxrate             int    `json:"errpkttxrate,omitempty"`
	Id                       string `json:"id,omitempty"`
	Interfacealias           string `json:"interfacealias,omitempty"`
	Jumbopktsreceived        int    `json:"jumbopktsreceived,omitempty"`
	Jumbopktsreceivedrate    int    `json:"jumbopktsreceivedrate,omitempty"`
	Jumbopktstransmitted     int    `json:"jumbopktstransmitted,omitempty"`
	Jumbopktstransmittedrate int    `json:"jumbopktstransmittedrate,omitempty"`
	Linkreinits              int    `json:"linkreinits,omitempty"`
	Macmovedrate             int    `json:"macmovedrate,omitempty"`
	Netscalerpktsrate        int    `json:"netscalerpktsrate,omitempty"`
	Nicerrdisables           int    `json:"nicerrdisables,omitempty"`
	Nicerrifoutdiscards      int    `json:"nicerrifoutdiscards,omitempty"`
	Nicerrifoutdiscardsrate  int    `json:"nicerrifoutdiscardsrate,omitempty"`
	Nicmulticastpktsrate     int    `json:"nicmulticastpktsrate,omitempty"`
	Nicrxstalls              int    `json:"nicrxstalls,omitempty"`
	Nicstsstalls             int    `json:"nicstsstalls,omitempty"`
	Nictotmulticastpkts      int    `json:"nictotmulticastpkts,omitempty"`
	Nictxstalls              int    `json:"nictxstalls,omitempty"`
	Rxbytesrate              int    `json:"rxbytesrate,omitempty"`
	Rxcrcerrors              int    `json:"rxcrcerrors,omitempty"`
	Rxcrcerrorsrate          int    `json:"rxcrcerrorsrate,omitempty"`
	Rxlacpdu                 int    `json:"rxlacpdu,omitempty"`
	Rxlacpdurate             int    `json:"rxlacpdurate,omitempty"`
	Rxpktsrate               int    `json:"rxpktsrate,omitempty"`
	Totmacmoved              int    `json:"totmacmoved,omitempty"`
	Totnetscalerpkts         int    `json:"totnetscalerpkts,omitempty"`
	Totrxbytes               int    `json:"totrxbytes,omitempty"`
	Totrxpkts                int    `json:"totrxpkts,omitempty"`
	Tottxbytes               int    `json:"tottxbytes,omitempty"`
	Tottxpkts                int    `json:"tottxpkts,omitempty"`
	Trunkpktsreceived        int    `json:"trunkpktsreceived,omitempty"`
	Trunkpktsreceivedrate    int    `json:"trunkpktsreceivedrate,omitempty"`
	Trunkpktstransmitted     int    `json:"trunkpktstransmitted,omitempty"`
	Trunkpktstransmittedrate int    `json:"trunkpktstransmittedrate,omitempty"`
	Txbytesrate              int    `json:"txbytesrate,omitempty"`
	Txlacpdu                 int    `json:"txlacpdu,omitempty"`
	Txlacpdurate             int    `json:"txlacpdurate,omitempty"`
	Txpktsrate               int    `json:"txpktsrate,omitempty"`
}
