package network

type Mapdomainstats struct {
	Clearstats           string      `json:"clearstats,omitempty"`
	Mapbmr               interface{} `json:"mapbmr,omitempty"`
	Maptotv4rxbytesicmp  int         `json:"maptotv4rxbytesicmp,omitempty"`
	Maptotv4rxbytestcp   int         `json:"maptotv4rxbytestcp,omitempty"`
	Maptotv4rxbytesudp   int         `json:"maptotv4rxbytesudp,omitempty"`
	Maptotv4rxpkts       int         `json:"maptotv4rxpkts,omitempty"`
	Maptotv4rxpktsicmp   int         `json:"maptotv4rxpktsicmp,omitempty"`
	Maptotv4rxpktstcp    int         `json:"maptotv4rxpktstcp,omitempty"`
	Maptotv4rxpktsudp    int         `json:"maptotv4rxpktsudp,omitempty"`
	Maptotv4txbytesicmp  int         `json:"maptotv4txbytesicmp,omitempty"`
	Maptotv4txbytestcp   int         `json:"maptotv4txbytestcp,omitempty"`
	Maptotv4txbytesudp   int         `json:"maptotv4txbytesudp,omitempty"`
	Maptotv4txpkts       int         `json:"maptotv4txpkts,omitempty"`
	Maptotv4txpktsicmp   int         `json:"maptotv4txpktsicmp,omitempty"`
	Maptotv4txpktstcp    int         `json:"maptotv4txpktstcp,omitempty"`
	Maptotv4txpktsudp    int         `json:"maptotv4txpktsudp,omitempty"`
	Maptotv6rxbytesicmp  int         `json:"maptotv6rxbytesicmp,omitempty"`
	Maptotv6rxbytestcp   int         `json:"maptotv6rxbytestcp,omitempty"`
	Maptotv6rxbytesudp   int         `json:"maptotv6rxbytesudp,omitempty"`
	Maptotv6rxpkts       int         `json:"maptotv6rxpkts,omitempty"`
	Maptotv6rxpktsicmp   int         `json:"maptotv6rxpktsicmp,omitempty"`
	Maptotv6rxpktstcp    int         `json:"maptotv6rxpktstcp,omitempty"`
	Maptotv6rxpktsudp    int         `json:"maptotv6rxpktsudp,omitempty"`
	Maptotv6txbytesicmp  int         `json:"maptotv6txbytesicmp,omitempty"`
	Maptotv6txbytestcp   int         `json:"maptotv6txbytestcp,omitempty"`
	Maptotv6txbytesudp   int         `json:"maptotv6txbytesudp,omitempty"`
	Maptotv6txpkts       int         `json:"maptotv6txpkts,omitempty"`
	Maptotv6txpktsicmp   int         `json:"maptotv6txpktsicmp,omitempty"`
	Maptotv6txpktstcp    int         `json:"maptotv6txpktstcp,omitempty"`
	Maptotv6txpktsudp    int         `json:"maptotv6txpktsudp,omitempty"`
	Mapv4rxbytesicmprate int         `json:"mapv4rxbytesicmprate,omitempty"`
	Mapv4rxbytestcprate  int         `json:"mapv4rxbytestcprate,omitempty"`
	Mapv4rxbytesudprate  int         `json:"mapv4rxbytesudprate,omitempty"`
	Mapv4rxpktsicmprate  int         `json:"mapv4rxpktsicmprate,omitempty"`
	Mapv4rxpktsrate      int         `json:"mapv4rxpktsrate,omitempty"`
	Mapv4rxpktstcprate   int         `json:"mapv4rxpktstcprate,omitempty"`
	Mapv4rxpktsudprate   int         `json:"mapv4rxpktsudprate,omitempty"`
	Mapv4txbytesicmprate int         `json:"mapv4txbytesicmprate,omitempty"`
	Mapv4txbytestcprate  int         `json:"mapv4txbytestcprate,omitempty"`
	Mapv4txbytesudprate  int         `json:"mapv4txbytesudprate,omitempty"`
	Mapv4txpktsicmprate  int         `json:"mapv4txpktsicmprate,omitempty"`
	Mapv4txpktsrate      int         `json:"mapv4txpktsrate,omitempty"`
	Mapv4txpktstcprate   int         `json:"mapv4txpktstcprate,omitempty"`
	Mapv4txpktsudprate   int         `json:"mapv4txpktsudprate,omitempty"`
	Mapv6rxbytesicmprate int         `json:"mapv6rxbytesicmprate,omitempty"`
	Mapv6rxbytestcprate  int         `json:"mapv6rxbytestcprate,omitempty"`
	Mapv6rxbytesudprate  int         `json:"mapv6rxbytesudprate,omitempty"`
	Mapv6rxpktsicmprate  int         `json:"mapv6rxpktsicmprate,omitempty"`
	Mapv6rxpktsrate      int         `json:"mapv6rxpktsrate,omitempty"`
	Mapv6rxpktstcprate   int         `json:"mapv6rxpktstcprate,omitempty"`
	Mapv6rxpktsudprate   int         `json:"mapv6rxpktsudprate,omitempty"`
	Mapv6txbytesicmprate int         `json:"mapv6txbytesicmprate,omitempty"`
	Mapv6txbytestcprate  int         `json:"mapv6txbytestcprate,omitempty"`
	Mapv6txbytesudprate  int         `json:"mapv6txbytesudprate,omitempty"`
	Mapv6txpktsicmprate  int         `json:"mapv6txpktsicmprate,omitempty"`
	Mapv6txpktsrate      int         `json:"mapv6txpktsrate,omitempty"`
	Mapv6txpktstcprate   int         `json:"mapv6txpktstcprate,omitempty"`
	Mapv6txpktsudprate   int         `json:"mapv6txpktsudprate,omitempty"`
	Name                 string      `json:"name,omitempty"`
}
