package appfw

type Appfwstats struct {
	Appfirewallaborts                                int    `json:"appfirewallaborts,omitempty"`
	Appfirewallabortsrate                            int    `json:"appfirewallabortsrate,omitempty"`
	Appfirewalllogbufferoverflow                     int    `json:"appfirewalllogbufferoverflow,omitempty"`
	Appfirewalllogbufferoverflowrate                 int    `json:"appfirewalllogbufferoverflowrate,omitempty"`
	Appfirewalllogcmd                                int    `json:"appfirewalllogcmd,omitempty"`
	Appfirewalllogcmdrate                            int    `json:"appfirewalllogcmdrate,omitempty"`
	Appfirewalllogcontenttype                        int    `json:"appfirewalllogcontenttype,omitempty"`
	Appfirewalllogcontenttyperate                    int    `json:"appfirewalllogcontenttyperate,omitempty"`
	Appfirewalllogcookie                             int    `json:"appfirewalllogcookie,omitempty"`
	Appfirewalllogcookiehijack                       int    `json:"appfirewalllogcookiehijack,omitempty"`
	Appfirewalllogcookiehijackrate                   int    `json:"appfirewalllogcookiehijackrate,omitempty"`
	Appfirewalllogcookierate                         int    `json:"appfirewalllogcookierate,omitempty"`
	Appfirewalllogcreditcard                         int    `json:"appfirewalllogcreditcard,omitempty"`
	Appfirewalllogcreditcardrate                     int    `json:"appfirewalllogcreditcardrate,omitempty"`
	Appfirewalllogcsrftag                            int    `json:"appfirewalllogcsrftag,omitempty"`
	Appfirewalllogcsrftagrate                        int    `json:"appfirewalllogcsrftagrate,omitempty"`
	Appfirewalllogdenyurl                            int    `json:"appfirewalllogdenyurl,omitempty"`
	Appfirewalllogdenyurlrate                        int    `json:"appfirewalllogdenyurlrate,omitempty"`
	Appfirewalllogfieldconsistency                   int    `json:"appfirewalllogfieldconsistency,omitempty"`
	Appfirewalllogfieldconsistencyrate               int    `json:"appfirewalllogfieldconsistencyrate,omitempty"`
	Appfirewalllogfieldformat                        int    `json:"appfirewalllogfieldformat,omitempty"`
	Appfirewalllogfieldformatrate                    int    `json:"appfirewalllogfieldformatrate,omitempty"`
	Appfirewalllogfileuploadtypes                    int    `json:"appfirewalllogfileuploadtypes,omitempty"`
	Appfirewalllogfileuploadtypesrate                int    `json:"appfirewalllogfileuploadtypesrate,omitempty"`
	Appfirewalllograte                               int    `json:"appfirewalllograte,omitempty"`
	Appfirewalllogrefererheader                      int    `json:"appfirewalllogrefererheader,omitempty"`
	Appfirewalllogrefererheaderrate                  int    `json:"appfirewalllogrefererheaderrate,omitempty"`
	Appfirewalllogsafeobject                         int    `json:"appfirewalllogsafeobject,omitempty"`
	Appfirewalllogsafeobjectrate                     int    `json:"appfirewalllogsafeobjectrate,omitempty"`
	Appfirewalllogsjsoncmd                           int    `json:"appfirewalllogsjsoncmd,omitempty"`
	Appfirewalllogsjsoncmdrate                       int    `json:"appfirewalllogsjsoncmdrate,omitempty"`
	Appfirewalllogsjsondos                           int    `json:"appfirewalllogsjsondos,omitempty"`
	Appfirewalllogsjsondosrate                       int    `json:"appfirewalllogsjsondosrate,omitempty"`
	Appfirewalllogsjsonsql                           int    `json:"appfirewalllogsjsonsql,omitempty"`
	Appfirewalllogsjsonsqlgram                       int    `json:"appfirewalllogsjsonsqlgram,omitempty"`
	Appfirewalllogsjsonsqlgramrate                   int    `json:"appfirewalllogsjsonsqlgramrate,omitempty"`
	Appfirewalllogsjsonsqlrate                       int    `json:"appfirewalllogsjsonsqlrate,omitempty"`
	Appfirewalllogsjsonxss                           int    `json:"appfirewalllogsjsonxss,omitempty"`
	Appfirewalllogsjsonxssrate                       int    `json:"appfirewalllogsjsonxssrate,omitempty"`
	Appfirewalllogsql                                int    `json:"appfirewalllogsql,omitempty"`
	Appfirewalllogsqlgram                            int    `json:"appfirewalllogsqlgram,omitempty"`
	Appfirewalllogsqlgramrate                        int    `json:"appfirewalllogsqlgramrate,omitempty"`
	Appfirewalllogsqlrate                            int    `json:"appfirewalllogsqlrate,omitempty"`
	Appfirewalllogstarturl                           int    `json:"appfirewalllogstarturl,omitempty"`
	Appfirewalllogstarturlrate                       int    `json:"appfirewalllogstarturlrate,omitempty"`
	Appfirewalllogtransformsql                       int    `json:"appfirewalllogtransformsql,omitempty"`
	Appfirewalllogtransformsqlrate                   int    `json:"appfirewalllogtransformsqlrate,omitempty"`
	Appfirewalllogtransformxss                       int    `json:"appfirewalllogtransformxss,omitempty"`
	Appfirewalllogtransformxssrate                   int    `json:"appfirewalllogtransformxssrate,omitempty"`
	Appfirewalllogxmlpayloadcontenttypemismatch      int    `json:"appfirewalllogxmlpayloadcontenttypemismatch,omitempty"`
	Appfirewalllogxmlpayloadcontenttypemismatchrate  int    `json:"appfirewalllogxmlpayloadcontenttypemismatchrate,omitempty"`
	Appfirewalllogxss                                int    `json:"appfirewalllogxss,omitempty"`
	Appfirewalllogxssrate                            int    `json:"appfirewalllogxssrate,omitempty"`
	Appfirewalllongavgresptime                       int    `json:"appfirewalllongavgresptime,omitempty"`
	Appfirewallmsgvallogs                            int    `json:"appfirewallmsgvallogs,omitempty"`
	Appfirewallmsgvallogsrate                        int    `json:"appfirewallmsgvallogsrate,omitempty"`
	Appfirewallpostbodylimitlogs                     int    `json:"appfirewallpostbodylimitlogs,omitempty"`
	Appfirewallpostbodylimitlogsrate                 int    `json:"appfirewallpostbodylimitlogsrate,omitempty"`
	Appfirewallpostbodylimitviolations               int    `json:"appfirewallpostbodylimitviolations,omitempty"`
	Appfirewallpostbodylimitviolationsrate           int    `json:"appfirewallpostbodylimitviolationsrate,omitempty"`
	Appfirewallredirects                             int    `json:"appfirewallredirects,omitempty"`
	Appfirewallredirectsrate                         int    `json:"appfirewallredirectsrate,omitempty"`
	Appfirewallreqbytes                              int    `json:"appfirewallreqbytes,omitempty"`
	Appfirewallreqbytesrate                          int    `json:"appfirewallreqbytesrate,omitempty"`
	Appfirewallrequests                              int    `json:"appfirewallrequests,omitempty"`
	Appfirewallrequestsrate                          int    `json:"appfirewallrequestsrate,omitempty"`
	Appfirewallresbytes                              int    `json:"appfirewallresbytes,omitempty"`
	Appfirewallresbytesrate                          int    `json:"appfirewallresbytesrate,omitempty"`
	Appfirewallresponses                             int    `json:"appfirewallresponses,omitempty"`
	Appfirewallresponsesrate                         int    `json:"appfirewallresponsesrate,omitempty"`
	Appfirewallret4xx                                int    `json:"appfirewallret4xx,omitempty"`
	Appfirewallret4xxrate                            int    `json:"appfirewallret4xxrate,omitempty"`
	Appfirewallret5xx                                int    `json:"appfirewallret5xx,omitempty"`
	Appfirewallret5xxrate                            int    `json:"appfirewallret5xxrate,omitempty"`
	Appfirewallshortavgresptime                      int    `json:"appfirewallshortavgresptime,omitempty"`
	Appfirewallsignaturelogs                         int    `json:"appfirewallsignaturelogs,omitempty"`
	Appfirewallsignaturelogsrate                     int    `json:"appfirewallsignaturelogsrate,omitempty"`
	Appfirewalltotallog                              int    `json:"appfirewalltotallog,omitempty"`
	Appfirewalltotalviol                             int    `json:"appfirewalltotalviol,omitempty"`
	Appfirewalltrapsdropped                          int    `json:"appfirewalltrapsdropped,omitempty"`
	Appfirewallviolbufferoverflow                    int    `json:"appfirewallviolbufferoverflow,omitempty"`
	Appfirewallviolbufferoverflowrate                int    `json:"appfirewallviolbufferoverflowrate,omitempty"`
	Appfirewallviolcmd                               int    `json:"appfirewallviolcmd,omitempty"`
	Appfirewallviolcmdrate                           int    `json:"appfirewallviolcmdrate,omitempty"`
	Appfirewallviolcontenttype                       int    `json:"appfirewallviolcontenttype,omitempty"`
	Appfirewallviolcontenttyperate                   int    `json:"appfirewallviolcontenttyperate,omitempty"`
	Appfirewallviolcookie                            int    `json:"appfirewallviolcookie,omitempty"`
	Appfirewallviolcookiehijack                      int    `json:"appfirewallviolcookiehijack,omitempty"`
	Appfirewallviolcookiehijackrate                  int    `json:"appfirewallviolcookiehijackrate,omitempty"`
	Appfirewallviolcookierate                        int    `json:"appfirewallviolcookierate,omitempty"`
	Appfirewallviolcreditcard                        int    `json:"appfirewallviolcreditcard,omitempty"`
	Appfirewallviolcreditcardrate                    int    `json:"appfirewallviolcreditcardrate,omitempty"`
	Appfirewallviolcsrftag                           int    `json:"appfirewallviolcsrftag,omitempty"`
	Appfirewallviolcsrftagrate                       int    `json:"appfirewallviolcsrftagrate,omitempty"`
	Appfirewallvioldenyurl                           int    `json:"appfirewallvioldenyurl,omitempty"`
	Appfirewallvioldenyurlrate                       int    `json:"appfirewallvioldenyurlrate,omitempty"`
	Appfirewallviolfieldconsistency                  int    `json:"appfirewallviolfieldconsistency,omitempty"`
	Appfirewallviolfieldconsistencyrate              int    `json:"appfirewallviolfieldconsistencyrate,omitempty"`
	Appfirewallviolfieldformat                       int    `json:"appfirewallviolfieldformat,omitempty"`
	Appfirewallviolfieldformatrate                   int    `json:"appfirewallviolfieldformatrate,omitempty"`
	Appfirewallviolfileuploadtypes                   int    `json:"appfirewallviolfileuploadtypes,omitempty"`
	Appfirewallviolfileuploadtypesrate               int    `json:"appfirewallviolfileuploadtypesrate,omitempty"`
	Appfirewallvioljsoncmd                           int    `json:"appfirewallvioljsoncmd,omitempty"`
	Appfirewallvioljsoncmdrate                       int    `json:"appfirewallvioljsoncmdrate,omitempty"`
	Appfirewallvioljsondos                           int    `json:"appfirewallvioljsondos,omitempty"`
	Appfirewallvioljsondosrate                       int    `json:"appfirewallvioljsondosrate,omitempty"`
	Appfirewallvioljsonsql                           int    `json:"appfirewallvioljsonsql,omitempty"`
	Appfirewallvioljsonsqlgram                       int    `json:"appfirewallvioljsonsqlgram,omitempty"`
	Appfirewallvioljsonsqlgramrate                   int    `json:"appfirewallvioljsonsqlgramrate,omitempty"`
	Appfirewallvioljsonsqlrate                       int    `json:"appfirewallvioljsonsqlrate,omitempty"`
	Appfirewallvioljsonxss                           int    `json:"appfirewallvioljsonxss,omitempty"`
	Appfirewallvioljsonxssrate                       int    `json:"appfirewallvioljsonxssrate,omitempty"`
	Appfirewallviolmsgvalviolations                  int    `json:"appfirewallviolmsgvalviolations,omitempty"`
	Appfirewallviolmsgvalviolationsrate              int    `json:"appfirewallviolmsgvalviolationsrate,omitempty"`
	Appfirewallviolrate                              int    `json:"appfirewallviolrate,omitempty"`
	Appfirewallviolrefererheader                     int    `json:"appfirewallviolrefererheader,omitempty"`
	Appfirewallviolrefererheaderrate                 int    `json:"appfirewallviolrefererheaderrate,omitempty"`
	Appfirewallviolsafeobject                        int    `json:"appfirewallviolsafeobject,omitempty"`
	Appfirewallviolsafeobjectrate                    int    `json:"appfirewallviolsafeobjectrate,omitempty"`
	Appfirewallviolsignature                         int    `json:"appfirewallviolsignature,omitempty"`
	Appfirewallviolsignaturerate                     int    `json:"appfirewallviolsignaturerate,omitempty"`
	Appfirewallviolsql                               int    `json:"appfirewallviolsql,omitempty"`
	Appfirewallviolsqlgram                           int    `json:"appfirewallviolsqlgram,omitempty"`
	Appfirewallviolsqlgramrate                       int    `json:"appfirewallviolsqlgramrate,omitempty"`
	Appfirewallviolsqlrate                           int    `json:"appfirewallviolsqlrate,omitempty"`
	Appfirewallviolstarturl                          int    `json:"appfirewallviolstarturl,omitempty"`
	Appfirewallviolstarturlrate                      int    `json:"appfirewallviolstarturlrate,omitempty"`
	Appfirewallviolwellformednessviolations          int    `json:"appfirewallviolwellformednessviolations,omitempty"`
	Appfirewallviolwellformednessviolationsrate      int    `json:"appfirewallviolwellformednessviolationsrate,omitempty"`
	Appfirewallviolwsiviolations                     int    `json:"appfirewallviolwsiviolations,omitempty"`
	Appfirewallviolwsiviolationsrate                 int    `json:"appfirewallviolwsiviolationsrate,omitempty"`
	Appfirewallviolxdosviolations                    int    `json:"appfirewallviolxdosviolations,omitempty"`
	Appfirewallviolxdosviolationsrate                int    `json:"appfirewallviolxdosviolationsrate,omitempty"`
	Appfirewallviolxmlattachmentviolations           int    `json:"appfirewallviolxmlattachmentviolations,omitempty"`
	Appfirewallviolxmlattachmentviolationsrate       int    `json:"appfirewallviolxmlattachmentviolationsrate,omitempty"`
	Appfirewallviolxmlgenviolations                  int    `json:"appfirewallviolxmlgenviolations,omitempty"`
	Appfirewallviolxmlgenviolationsrate              int    `json:"appfirewallviolxmlgenviolationsrate,omitempty"`
	Appfirewallviolxmlpayloadcontenttypemismatch     int    `json:"appfirewallviolxmlpayloadcontenttypemismatch,omitempty"`
	Appfirewallviolxmlpayloadcontenttypemismatchrate int    `json:"appfirewallviolxmlpayloadcontenttypemismatchrate,omitempty"`
	Appfirewallviolxmlsoapfaultviolations            int    `json:"appfirewallviolxmlsoapfaultviolations,omitempty"`
	Appfirewallviolxmlsoapfaultviolationsrate        int    `json:"appfirewallviolxmlsoapfaultviolationsrate,omitempty"`
	Appfirewallviolxmlsqlviolations                  int    `json:"appfirewallviolxmlsqlviolations,omitempty"`
	Appfirewallviolxmlsqlviolationsrate              int    `json:"appfirewallviolxmlsqlviolationsrate,omitempty"`
	Appfirewallviolxmlxssviolations                  int    `json:"appfirewallviolxmlxssviolations,omitempty"`
	Appfirewallviolxmlxssviolationsrate              int    `json:"appfirewallviolxmlxssviolationsrate,omitempty"`
	Appfirewallviolxss                               int    `json:"appfirewallviolxss,omitempty"`
	Appfirewallviolxssrate                           int    `json:"appfirewallviolxssrate,omitempty"`
	Appfirewallwellformednesslogs                    int    `json:"appfirewallwellformednesslogs,omitempty"`
	Appfirewallwellformednesslogsrate                int    `json:"appfirewallwellformednesslogsrate,omitempty"`
	Appfirewallwsilogs                               int    `json:"appfirewallwsilogs,omitempty"`
	Appfirewallwsilogsrate                           int    `json:"appfirewallwsilogsrate,omitempty"`
	Appfirewallxdoslogs                              int    `json:"appfirewallxdoslogs,omitempty"`
	Appfirewallxdoslogsrate                          int    `json:"appfirewallxdoslogsrate,omitempty"`
	Appfirewallxmlattachmentlogs                     int    `json:"appfirewallxmlattachmentlogs,omitempty"`
	Appfirewallxmlattachmentlogsrate                 int    `json:"appfirewallxmlattachmentlogsrate,omitempty"`
	Appfirewallxmlgenlogs                            int    `json:"appfirewallxmlgenlogs,omitempty"`
	Appfirewallxmlgenlogsrate                        int    `json:"appfirewallxmlgenlogsrate,omitempty"`
	Appfirewallxmlsoapfaultlogs                      int    `json:"appfirewallxmlsoapfaultlogs,omitempty"`
	Appfirewallxmlsoapfaultlogsrate                  int    `json:"appfirewallxmlsoapfaultlogsrate,omitempty"`
	Appfirewallxmlsqllogs                            int    `json:"appfirewallxmlsqllogs,omitempty"`
	Appfirewallxmlsqllogsrate                        int    `json:"appfirewallxmlsqllogsrate,omitempty"`
	Appfirewallxmlxsslogs                            int    `json:"appfirewallxmlxsslogs,omitempty"`
	Appfirewallxmlxsslogsrate                        int    `json:"appfirewallxmlxsslogsrate,omitempty"`
	Clearstats                                       string `json:"clearstats,omitempty"`
}
