package ssl

type Sslstats struct {
	Clearstats                              string  `json:"clearstats,omitempty"`
	Ssl128bitaesgcmciphersrate              int     `json:"ssl128bitaesgcmciphersrate,omitempty"`
	Ssl128bitideaciphersrate                int     `json:"ssl128bitideaciphersrate,omitempty"`
	Ssl128bitrc2ciphersrate                 int     `json:"ssl128bitrc2ciphersrate,omitempty"`
	Ssl128bitrc4ciphersrate                 int     `json:"ssl128bitrc4ciphersrate,omitempty"`
	Ssl168bit3desciphersrate                int     `json:"ssl168bit3desciphersrate,omitempty"`
	Ssl256bitaesgcmciphersrate              int     `json:"ssl256bitaesgcmciphersrate,omitempty"`
	Ssl40bitdesciphersrate                  int     `json:"ssl40bitdesciphersrate,omitempty"`
	Ssl40bitrc2ciphersrate                  int     `json:"ssl40bitrc2ciphersrate,omitempty"`
	Ssl40bitrc4ciphersrate                  int     `json:"ssl40bitrc4ciphersrate,omitempty"`
	Ssl56bitdesciphersrate                  int     `json:"ssl56bitdesciphersrate,omitempty"`
	Ssl56bitrc2ciphersrate                  int     `json:"ssl56bitrc2ciphersrate,omitempty"`
	Ssl56bitrc4ciphersrate                  int     `json:"ssl56bitrc4ciphersrate,omitempty"`
	Ssl64bitrc4ciphersrate                  int     `json:"ssl64bitrc4ciphersrate,omitempty"`
	Sslbe128bitideaciphersrate              int     `json:"sslbe128bitideaciphersrate,omitempty"`
	Sslbe128bitrc2ciphersrate               int     `json:"sslbe128bitrc2ciphersrate,omitempty"`
	Sslbe128bitrc4ciphersrate               int     `json:"sslbe128bitrc4ciphersrate,omitempty"`
	Sslbe168bit3desciphersrate              int     `json:"sslbe168bit3desciphersrate,omitempty"`
	Sslbe40bitdesciphersrate                int     `json:"sslbe40bitdesciphersrate,omitempty"`
	Sslbe40bitrc2ciphersrate                int     `json:"sslbe40bitrc2ciphersrate,omitempty"`
	Sslbe40bitrc4ciphersrate                int     `json:"sslbe40bitrc4ciphersrate,omitempty"`
	Sslbe56bitdesciphersrate                int     `json:"sslbe56bitdesciphersrate,omitempty"`
	Sslbe56bitrc2ciphersrate                int     `json:"sslbe56bitrc2ciphersrate,omitempty"`
	Sslbe56bitrc4ciphersrate                int     `json:"sslbe56bitrc4ciphersrate,omitempty"`
	Sslbe64bitrc4ciphersrate                int     `json:"sslbe64bitrc4ciphersrate,omitempty"`
	Sslbedh1024keyexchangesrate             int     `json:"sslbedh1024keyexchangesrate,omitempty"`
	Sslbedh2048keyexchangesrate             int     `json:"sslbedh2048keyexchangesrate,omitempty"`
	Sslbedh4096keyexchangesrate             int     `json:"sslbedh4096keyexchangesrate,omitempty"`
	Sslbedh512keyexchangesrate              int     `json:"sslbedh512keyexchangesrate,omitempty"`
	Sslbedhauthorizationsrate               int     `json:"sslbedhauthorizationsrate,omitempty"`
	Sslbedssauthorizationsrate              int     `json:"sslbedssauthorizationsrate,omitempty"`
	Sslbedtlsv1clientauthenticationsrate    int     `json:"sslbedtlsv1clientauthenticationsrate,omitempty"`
	Sslbedtlsv1handshakesrate               int     `json:"sslbedtlsv1handshakesrate,omitempty"`
	Sslbedtlsv1sessionsrate                 int     `json:"sslbedtlsv1sessionsrate,omitempty"`
	Sslbeecdhecurve224rate                  int     `json:"sslbeecdhecurve224rate,omitempty"`
	Sslbeecdhecurve256rate                  int     `json:"sslbeecdhecurve256rate,omitempty"`
	Sslbeecdhecurve384rate                  int     `json:"sslbeecdhecurve384rate,omitempty"`
	Sslbeecdhecurve521rate                  int     `json:"sslbeecdhecurve521rate,omitempty"`
	Sslbeecdsaauthorizationsrate            int     `json:"sslbeecdsaauthorizationsrate,omitempty"`
	Sslbemaxmultiplexedsessions             int     `json:"sslbemaxmultiplexedsessions,omitempty"`
	Sslbemaxmultiplexedsessionsrate         int     `json:"sslbemaxmultiplexedsessionsrate,omitempty"`
	Sslbemd5macrate                         int     `json:"sslbemd5macrate,omitempty"`
	Sslbenullauthorizationsrate             int     `json:"sslbenullauthorizationsrate,omitempty"`
	Sslbenullciphersrate                    int     `json:"sslbenullciphersrate,omitempty"`
	Sslbersa1024keyexchangesrate            int     `json:"sslbersa1024keyexchangesrate,omitempty"`
	Sslbersa2048keyexchangesrate            int     `json:"sslbersa2048keyexchangesrate,omitempty"`
	Sslbersa3072keyexchangesrate            int     `json:"sslbersa3072keyexchangesrate,omitempty"`
	Sslbersa4096keyexchangesrate            int     `json:"sslbersa4096keyexchangesrate,omitempty"`
	Sslbersa512keyexchangesrate             int     `json:"sslbersa512keyexchangesrate,omitempty"`
	Sslbersaauthorizationsrate              int     `json:"sslbersaauthorizationsrate,omitempty"`
	Sslbesessionmultiplexattemptfailsrate   int     `json:"sslbesessionmultiplexattemptfailsrate,omitempty"`
	Sslbesessionmultiplexattemptsrate       int     `json:"sslbesessionmultiplexattemptsrate,omitempty"`
	Sslbesessionmultiplexattemptsuccessrate int     `json:"sslbesessionmultiplexattemptsuccessrate,omitempty"`
	Sslbesessionsrate                       int     `json:"sslbesessionsrate,omitempty"`
	Sslbesha256macrate                      int     `json:"sslbesha256macrate,omitempty"`
	Sslbesha384macrate                      int     `json:"sslbesha384macrate,omitempty"`
	Sslbeshamacrate                         int     `json:"sslbeshamacrate,omitempty"`
	Sslbesslv3clientauthenticationsrate     int     `json:"sslbesslv3clientauthenticationsrate,omitempty"`
	Sslbesslv3handshakesrate                int     `json:"sslbesslv3handshakesrate,omitempty"`
	Sslbesslv3sessionsrate                  int     `json:"sslbesslv3sessionsrate,omitempty"`
	Sslbetlsv11clientauthenticationsrate    int     `json:"sslbetlsv11clientauthenticationsrate,omitempty"`
	Sslbetlsv11handshakesrate               int     `json:"sslbetlsv11handshakesrate,omitempty"`
	Sslbetlsv11sessionsrate                 int     `json:"sslbetlsv11sessionsrate,omitempty"`
	Sslbetlsv12clientauthenticationsrate    int     `json:"sslbetlsv12clientauthenticationsrate,omitempty"`
	Sslbetlsv12handshakesrate               int     `json:"sslbetlsv12handshakesrate,omitempty"`
	Sslbetlsv12sessionsrate                 int     `json:"sslbetlsv12sessionsrate,omitempty"`
	Sslbetlsv1clientauthenticationsrate     int     `json:"sslbetlsv1clientauthenticationsrate,omitempty"`
	Sslbetlsv1handshakesrate                int     `json:"sslbetlsv1handshakesrate,omitempty"`
	Sslbetlsv1sessionsrate                  int     `json:"sslbetlsv1sessionsrate,omitempty"`
	Sslbetot128bitideaciphers               int     `json:"sslbetot128bitideaciphers,omitempty"`
	Sslbetot128bitrc2ciphers                int     `json:"sslbetot128bitrc2ciphers,omitempty"`
	Sslbetot128bitrc4ciphers                int     `json:"sslbetot128bitrc4ciphers,omitempty"`
	Sslbetot168bit3desciphers               int     `json:"sslbetot168bit3desciphers,omitempty"`
	Sslbetot40bitdesciphers                 int     `json:"sslbetot40bitdesciphers,omitempty"`
	Sslbetot40bitrc2ciphers                 int     `json:"sslbetot40bitrc2ciphers,omitempty"`
	Sslbetot40bitrc4ciphers                 int     `json:"sslbetot40bitrc4ciphers,omitempty"`
	Sslbetot56bitdesciphers                 int     `json:"sslbetot56bitdesciphers,omitempty"`
	Sslbetot56bitrc2ciphers                 int     `json:"sslbetot56bitrc2ciphers,omitempty"`
	Sslbetot56bitrc4ciphers                 int     `json:"sslbetot56bitrc4ciphers,omitempty"`
	Sslbetot64bitrc4ciphers                 int     `json:"sslbetot64bitrc4ciphers,omitempty"`
	Sslbetotdh1024keyexchanges              int     `json:"sslbetotdh1024keyexchanges,omitempty"`
	Sslbetotdh2048keyexchanges              int     `json:"sslbetotdh2048keyexchanges,omitempty"`
	Sslbetotdh4096keyexchanges              int     `json:"sslbetotdh4096keyexchanges,omitempty"`
	Sslbetotdh512keyexchanges               int     `json:"sslbetotdh512keyexchanges,omitempty"`
	Sslbetotdhauthorizations                int     `json:"sslbetotdhauthorizations,omitempty"`
	Sslbetotdssauthorizations               int     `json:"sslbetotdssauthorizations,omitempty"`
	Sslbetotdtlsv1clientauthentications     int     `json:"sslbetotdtlsv1clientauthentications,omitempty"`
	Sslbetotdtlsv1handshakes                int     `json:"sslbetotdtlsv1handshakes,omitempty"`
	Sslbetotdtlsv1sessions                  int     `json:"sslbetotdtlsv1sessions,omitempty"`
	Sslbetotecdhecurve224                   int     `json:"sslbetotecdhecurve224,omitempty"`
	Sslbetotecdhecurve256                   int     `json:"sslbetotecdhecurve256,omitempty"`
	Sslbetotecdhecurve384                   int     `json:"sslbetotecdhecurve384,omitempty"`
	Sslbetotecdhecurve521                   int     `json:"sslbetotecdhecurve521,omitempty"`
	Sslbetotecdsaauthorizations             int     `json:"sslbetotecdsaauthorizations,omitempty"`
	Sslbetotmd5mac                          int     `json:"sslbetotmd5mac,omitempty"`
	Sslbetotnullauthorizations              int     `json:"sslbetotnullauthorizations,omitempty"`
	Sslbetotnullciphers                     int     `json:"sslbetotnullciphers,omitempty"`
	Sslbetotrsa1024keyexchanges             int     `json:"sslbetotrsa1024keyexchanges,omitempty"`
	Sslbetotrsa2048keyexchanges             int     `json:"sslbetotrsa2048keyexchanges,omitempty"`
	Sslbetotrsa3072keyexchanges             int     `json:"sslbetotrsa3072keyexchanges,omitempty"`
	Sslbetotrsa4096keyexchanges             int     `json:"sslbetotrsa4096keyexchanges,omitempty"`
	Sslbetotrsa512keyexchanges              int     `json:"sslbetotrsa512keyexchanges,omitempty"`
	Sslbetotrsaauthorizations               int     `json:"sslbetotrsaauthorizations,omitempty"`
	Sslbetotsessionmultiplexattemptfails    int     `json:"sslbetotsessionmultiplexattemptfails,omitempty"`
	Sslbetotsessionmultiplexattempts        int     `json:"sslbetotsessionmultiplexattempts,omitempty"`
	Sslbetotsessionmultiplexattemptsuccess  int     `json:"sslbetotsessionmultiplexattemptsuccess,omitempty"`
	Sslbetotsessions                        int     `json:"sslbetotsessions,omitempty"`
	Sslbetotsha256mac                       int     `json:"sslbetotsha256mac,omitempty"`
	Sslbetotsha384mac                       int     `json:"sslbetotsha384mac,omitempty"`
	Sslbetotshamac                          int     `json:"sslbetotshamac,omitempty"`
	Sslbetotsslv3clientauthentications      int     `json:"sslbetotsslv3clientauthentications,omitempty"`
	Sslbetotsslv3handshakes                 int     `json:"sslbetotsslv3handshakes,omitempty"`
	Sslbetotsslv3sessions                   int     `json:"sslbetotsslv3sessions,omitempty"`
	Sslbetottlsv11clientauthentications     int     `json:"sslbetottlsv11clientauthentications,omitempty"`
	Sslbetottlsv11handshakes                int     `json:"sslbetottlsv11handshakes,omitempty"`
	Sslbetottlsv11sessions                  int     `json:"sslbetottlsv11sessions,omitempty"`
	Sslbetottlsv12clientauthentications     int     `json:"sslbetottlsv12clientauthentications,omitempty"`
	Sslbetottlsv12handshakes                int     `json:"sslbetottlsv12handshakes,omitempty"`
	Sslbetottlsv12sessions                  int     `json:"sslbetottlsv12sessions,omitempty"`
	Sslbetottlsv1clientauthentications      int     `json:"sslbetottlsv1clientauthentications,omitempty"`
	Sslbetottlsv1handshakes                 int     `json:"sslbetottlsv1handshakes,omitempty"`
	Sslbetottlsv1sessions                   int     `json:"sslbetottlsv1sessions,omitempty"`
	Sslbkendcipheraes128rate                int     `json:"sslbkendcipheraes128rate,omitempty"`
	Sslbkendcipheraes256rate                int     `json:"sslbkendcipheraes256rate,omitempty"`
	Sslbkendcipheraesgcm128rate             int     `json:"sslbkendcipheraesgcm128rate,omitempty"`
	Sslbkendcipheraesgcm256rate             int     `json:"sslbkendcipheraesgcm256rate,omitempty"`
	Sslbkenddtlsvlrenegorate                int     `json:"sslbkenddtlsvlrenegorate,omitempty"`
	Sslbkendsessionrenegotiaterate          int     `json:"sslbkendsessionrenegotiaterate,omitempty"`
	Sslbkendsslv3renegorate                 int     `json:"sslbkendsslv3renegorate,omitempty"`
	Sslbkendtlsv11renegorate                int     `json:"sslbkendtlsv11renegorate,omitempty"`
	Sslbkendtlsv12renegorate                int     `json:"sslbkendtlsv12renegorate,omitempty"`
	Sslbkendtlsvlrenegorate                 int     `json:"sslbkendtlsvlrenegorate,omitempty"`
	Sslcards                                int     `json:"sslcards,omitempty"`
	Sslcardssecondary                       int     `json:"sslcardssecondary,omitempty"`
	Sslcardstatus                           int     `json:"sslcardstatus,omitempty"`
	Sslcipheraes128rate                     int     `json:"sslcipheraes128rate,omitempty"`
	Sslcipheraes256rate                     int     `json:"sslcipheraes256rate,omitempty"`
	Sslcryptoutilizationasymstat            int     `json:"sslcryptoutilizationasymstat,omitempty"`
	Sslcryptoutilizationstat                float64 `json:"sslcryptoutilizationstat,omitempty"`
	Sslcryptoutilizationstat2nd             float64 `json:"sslcryptoutilizationstat2nd,omitempty"`
	Sslcryptoutilizationsymmstat            int     `json:"sslcryptoutilizationsymmstat,omitempty"`
	Sslcurqsize                             int     `json:"sslcurqsize,omitempty"`
	Sslcurqsizerate                         int     `json:"sslcurqsizerate,omitempty"`
	Sslcursessions                          int     `json:"sslcursessions,omitempty"`
	Sslcursessionsrate                      int     `json:"sslcursessionsrate,omitempty"`
	Sslcursslinfocardinblkq                 int     `json:"sslcursslinfocardinblkq,omitempty"`
	Sslcursslinfocardinblkqrate             int     `json:"sslcursslinfocardinblkqrate,omitempty"`
	Sslcursslinfocardinkeyq                 int     `json:"sslcursslinfocardinkeyq,omitempty"`
	Sslcursslinfocardinkeyqrate             int     `json:"sslcursslinfocardinkeyqrate,omitempty"`
	Sslcursslinfonscardinqcount             int     `json:"sslcursslinfonscardinqcount,omitempty"`
	Sslcursslinfonscardinqcountrate         int     `json:"sslcursslinfonscardinqcountrate,omitempty"`
	Sslcursslinfospcbinusecount             int     `json:"sslcursslinfospcbinusecount,omitempty"`
	Sslcursslinfospcbinusecountrate         int     `json:"sslcursslinfospcbinusecountrate,omitempty"`
	Ssldecberate                            int     `json:"ssldecberate,omitempty"`
	Ssldecferate                            int     `json:"ssldecferate,omitempty"`
	Ssldechwrate                            int     `json:"ssldechwrate,omitempty"`
	Ssldechwsecondaryrate                   int     `json:"ssldechwsecondaryrate,omitempty"`
	Ssldecrate                              int     `json:"ssldecrate,omitempty"`
	Ssldecswrate                            int     `json:"ssldecswrate,omitempty"`
	Ssldh1024keyexchangesrate               int     `json:"ssldh1024keyexchangesrate,omitempty"`
	Ssldh2048keyexchangesrate               int     `json:"ssldh2048keyexchangesrate,omitempty"`
	Ssldh4096keyexchangesrate               int     `json:"ssldh4096keyexchangesrate,omitempty"`
	Ssldh512keyexchangesrate                int     `json:"ssldh512keyexchangesrate,omitempty"`
	Ssldhauthorizationsrate                 int     `json:"ssldhauthorizationsrate,omitempty"`
	Ssldssauthorizationsrate                int     `json:"ssldssauthorizationsrate,omitempty"`
	Ssldtlsv12clientauthenticationsrate     int     `json:"ssldtlsv12clientauthenticationsrate,omitempty"`
	Ssldtlsv12handshakesrate                int     `json:"ssldtlsv12handshakesrate,omitempty"`
	Ssldtlsv12renegsessionsrate             int     `json:"ssldtlsv12renegsessionsrate,omitempty"`
	Ssldtlsv12sessionsrate                  int     `json:"ssldtlsv12sessionsrate,omitempty"`
	Ssldtlsv12transactionsrate              int     `json:"ssldtlsv12transactionsrate,omitempty"`
	Ssldtlsv1clientauthenticationsrate      int     `json:"ssldtlsv1clientauthenticationsrate,omitempty"`
	Ssldtlsv1handshakesrate                 int     `json:"ssldtlsv1handshakesrate,omitempty"`
	Ssldtlsv1renegsessionsrate              int     `json:"ssldtlsv1renegsessionsrate,omitempty"`
	Ssldtlsv1sessionsrate                   int     `json:"ssldtlsv1sessionsrate,omitempty"`
	Ssldtlsv1transactionsrate               int     `json:"ssldtlsv1transactionsrate,omitempty"`
	Sslecdhe224keyexchangesrate             int     `json:"sslecdhe224keyexchangesrate,omitempty"`
	Sslecdhe256keyexchangesrate             int     `json:"sslecdhe256keyexchangesrate,omitempty"`
	Sslecdhe384keyexchangesrate             int     `json:"sslecdhe384keyexchangesrate,omitempty"`
	Sslecdhe521keyexchangesrate             int     `json:"sslecdhe521keyexchangesrate,omitempty"`
	Sslecdhetransactionsrate                int     `json:"sslecdhetransactionsrate,omitempty"`
	Sslecdsaauthorizationsrate              int     `json:"sslecdsaauthorizationsrate,omitempty"`
	Sslencberate                            int     `json:"sslencberate,omitempty"`
	Sslencferate                            int     `json:"sslencferate,omitempty"`
	Sslenchwrate                            int     `json:"sslenchwrate,omitempty"`
	Sslenchwsecondaryrate                   int     `json:"sslenchwsecondaryrate,omitempty"`
	Sslencrate                              int     `json:"sslencrate,omitempty"`
	Sslencswrate                            int     `json:"sslencswrate,omitempty"`
	Sslenginestatus                         int     `json:"sslenginestatus,omitempty"`
	Sslhwdecberate                          int     `json:"sslhwdecberate,omitempty"`
	Sslhwdecbesecondaryrate                 int     `json:"sslhwdecbesecondaryrate,omitempty"`
	Sslhwdecferate                          int     `json:"sslhwdecferate,omitempty"`
	Sslhwdecfesecondaryrate                 int     `json:"sslhwdecfesecondaryrate,omitempty"`
	Sslhwencberate                          int     `json:"sslhwencberate,omitempty"`
	Sslhwencbesecondaryrate                 int     `json:"sslhwencbesecondaryrate,omitempty"`
	Sslhwencferate                          int     `json:"sslhwencferate,omitempty"`
	Sslhwencfesecondaryrate                 int     `json:"sslhwencfesecondaryrate,omitempty"`
	Sslmd5macrate                           int     `json:"sslmd5macrate,omitempty"`
	Sslnewsessionsrate                      int     `json:"sslnewsessionsrate,omitempty"`
	Sslnullauthorizationsrate               int     `json:"sslnullauthorizationsrate,omitempty"`
	Sslnullciphersrate                      int     `json:"sslnullciphersrate,omitempty"`
	Sslnumcardsup                           int     `json:"sslnumcardsup,omitempty"`
	Sslnumcardsupsecondary                  int     `json:"sslnumcardsupsecondary,omitempty"`
	Ssloffloadbulkaesgcm128rate             int     `json:"ssloffloadbulkaesgcm128rate,omitempty"`
	Ssloffloadbulkaesgcm256rate             int     `json:"ssloffloadbulkaesgcm256rate,omitempty"`
	Ssloffloadbulkaesrate                   int     `json:"ssloffloadbulkaesrate,omitempty"`
	Ssloffloadbulkdesrate                   int     `json:"ssloffloadbulkdesrate,omitempty"`
	Ssloffloadbulkrc4rate                   int     `json:"ssloffloadbulkrc4rate,omitempty"`
	Ssloffloaddhkeyexchangesrate            int     `json:"ssloffloaddhkeyexchangesrate,omitempty"`
	Ssloffloadrsakeyexchangesrate           int     `json:"ssloffloadrsakeyexchangesrate,omitempty"`
	Ssloffloadsignrsarate                   int     `json:"ssloffloadsignrsarate,omitempty"`
	Sslrenegsessionsrate                    int     `json:"sslrenegsessionsrate,omitempty"`
	Sslrsa1024keyexchangesrate              int     `json:"sslrsa1024keyexchangesrate,omitempty"`
	Sslrsa2048keyexchangesrate              int     `json:"sslrsa2048keyexchangesrate,omitempty"`
	Sslrsa3072keyexchangesrate              int     `json:"sslrsa3072keyexchangesrate,omitempty"`
	Sslrsa4096keyexchangesrate              int     `json:"sslrsa4096keyexchangesrate,omitempty"`
	Sslrsa512keyexchangesrate               int     `json:"sslrsa512keyexchangesrate,omitempty"`
	Sslrsaauthorizationsrate                int     `json:"sslrsaauthorizationsrate,omitempty"`
	Sslsessionhitsrate                      int     `json:"sslsessionhitsrate,omitempty"`
	Sslsessionmissrate                      int     `json:"sslsessionmissrate,omitempty"`
	Sslsessionsrate                         int     `json:"sslsessionsrate,omitempty"`
	Sslsha256macrate                        int     `json:"sslsha256macrate,omitempty"`
	Sslsha384macrate                        int     `json:"sslsha384macrate,omitempty"`
	Sslshamacrate                           int     `json:"sslshamacrate,omitempty"`
	Sslsslserverinrecordsrate               int     `json:"sslsslserverinrecordsrate,omitempty"`
	Sslsslv2clientauthenticationsrate       int     `json:"sslsslv2clientauthenticationsrate,omitempty"`
	Sslsslv2handshakesrate                  int     `json:"sslsslv2handshakesrate,omitempty"`
	Sslsslv2sessionsrate                    int     `json:"sslsslv2sessionsrate,omitempty"`
	Sslsslv2transactionsrate                int     `json:"sslsslv2transactionsrate,omitempty"`
	Sslsslv3clientauthenticationsrate       int     `json:"sslsslv3clientauthenticationsrate,omitempty"`
	Sslsslv3handshakesrate                  int     `json:"sslsslv3handshakesrate,omitempty"`
	Sslsslv3renegsessionsrate               int     `json:"sslsslv3renegsessionsrate,omitempty"`
	Sslsslv3sessionsrate                    int     `json:"sslsslv3sessionsrate,omitempty"`
	Sslsslv3transactionsrate                int     `json:"sslsslv3transactionsrate,omitempty"`
	Sslswdecberate                          int     `json:"sslswdecberate,omitempty"`
	Sslswdecferate                          int     `json:"sslswdecferate,omitempty"`
	Sslswencberate                          int     `json:"sslswencberate,omitempty"`
	Sslswencferate                          int     `json:"sslswencferate,omitempty"`
	Ssltlsv11clientauthenticationsrate      int     `json:"ssltlsv11clientauthenticationsrate,omitempty"`
	Ssltlsv11handshakesrate                 int     `json:"ssltlsv11handshakesrate,omitempty"`
	Ssltlsv11renegsessionsrate              int     `json:"ssltlsv11renegsessionsrate,omitempty"`
	Ssltlsv11sessionsrate                   int     `json:"ssltlsv11sessionsrate,omitempty"`
	Ssltlsv11transactionsrate               int     `json:"ssltlsv11transactionsrate,omitempty"`
	Ssltlsv12clientauthenticationsrate      int     `json:"ssltlsv12clientauthenticationsrate,omitempty"`
	Ssltlsv12handshakesrate                 int     `json:"ssltlsv12handshakesrate,omitempty"`
	Ssltlsv12renegsessionsrate              int     `json:"ssltlsv12renegsessionsrate,omitempty"`
	Ssltlsv12sessionsrate                   int     `json:"ssltlsv12sessionsrate,omitempty"`
	Ssltlsv12transactionsrate               int     `json:"ssltlsv12transactionsrate,omitempty"`
	Ssltlsv13clientauthenticationsrate      int     `json:"ssltlsv13clientauthenticationsrate,omitempty"`
	Ssltlsv13handshakesrate                 int     `json:"ssltlsv13handshakesrate,omitempty"`
	Ssltlsv13sessionsrate                   int     `json:"ssltlsv13sessionsrate,omitempty"`
	Ssltlsv13transactionsrate               int     `json:"ssltlsv13transactionsrate,omitempty"`
	Ssltlsv1clientauthenticationsrate       int     `json:"ssltlsv1clientauthenticationsrate,omitempty"`
	Ssltlsv1handshakesrate                  int     `json:"ssltlsv1handshakesrate,omitempty"`
	Ssltlsv1renegsessionsrate               int     `json:"ssltlsv1renegsessionsrate,omitempty"`
	Ssltlsv1sessionsrate                    int     `json:"ssltlsv1sessionsrate,omitempty"`
	Ssltlsv1transactionsrate                int     `json:"ssltlsv1transactionsrate,omitempty"`
	Ssltot128bitaesgcmciphers               int     `json:"ssltot128bitaesgcmciphers,omitempty"`
	Ssltot128bitideaciphers                 int     `json:"ssltot128bitideaciphers,omitempty"`
	Ssltot128bitrc2ciphers                  int     `json:"ssltot128bitrc2ciphers,omitempty"`
	Ssltot128bitrc4ciphers                  int     `json:"ssltot128bitrc4ciphers,omitempty"`
	Ssltot168bit3desciphers                 int     `json:"ssltot168bit3desciphers,omitempty"`
	Ssltot256bitaesgcmciphers               int     `json:"ssltot256bitaesgcmciphers,omitempty"`
	Ssltot40bitdesciphers                   int     `json:"ssltot40bitdesciphers,omitempty"`
	Ssltot40bitrc2ciphers                   int     `json:"ssltot40bitrc2ciphers,omitempty"`
	Ssltot40bitrc4ciphers                   int     `json:"ssltot40bitrc4ciphers,omitempty"`
	Ssltot56bitdesciphers                   int     `json:"ssltot56bitdesciphers,omitempty"`
	Ssltot56bitrc2ciphers                   int     `json:"ssltot56bitrc2ciphers,omitempty"`
	Ssltot56bitrc4ciphers                   int     `json:"ssltot56bitrc4ciphers,omitempty"`
	Ssltot64bitrc4ciphers                   int     `json:"ssltot64bitrc4ciphers,omitempty"`
	Ssltotbkendcipheraes128                 int     `json:"ssltotbkendcipheraes128,omitempty"`
	Ssltotbkendcipheraes256                 int     `json:"ssltotbkendcipheraes256,omitempty"`
	Ssltotbkendcipheraesgcm128              int     `json:"ssltotbkendcipheraesgcm128,omitempty"`
	Ssltotbkendcipheraesgcm256              int     `json:"ssltotbkendcipheraesgcm256,omitempty"`
	Ssltotbkenddtlsvlrenego                 int     `json:"ssltotbkenddtlsvlrenego,omitempty"`
	Ssltotbkendsessionrenegotiate           int     `json:"ssltotbkendsessionrenegotiate,omitempty"`
	Ssltotbkendsslv3renego                  int     `json:"ssltotbkendsslv3renego,omitempty"`
	Ssltotbkendtlsv11renego                 int     `json:"ssltotbkendtlsv11renego,omitempty"`
	Ssltotbkendtlsv12renego                 int     `json:"ssltotbkendtlsv12renego,omitempty"`
	Ssltotbkendtlsvlrenego                  int     `json:"ssltotbkendtlsvlrenego,omitempty"`
	Ssltotcipheraes128                      int     `json:"ssltotcipheraes128,omitempty"`
	Ssltotcipheraes256                      int     `json:"ssltotcipheraes256,omitempty"`
	Ssltotdec                               int     `json:"ssltotdec,omitempty"`
	Ssltotdecbe                             int     `json:"ssltotdecbe,omitempty"`
	Ssltotdecfe                             int     `json:"ssltotdecfe,omitempty"`
	Ssltotdechw                             int     `json:"ssltotdechw,omitempty"`
	Ssltotdechwsecondary                    int     `json:"ssltotdechwsecondary,omitempty"`
	Ssltotdecsw                             int     `json:"ssltotdecsw,omitempty"`
	Ssltotdh1024keyexchanges                int     `json:"ssltotdh1024keyexchanges,omitempty"`
	Ssltotdh2048keyexchanges                int     `json:"ssltotdh2048keyexchanges,omitempty"`
	Ssltotdh4096keyexchanges                int     `json:"ssltotdh4096keyexchanges,omitempty"`
	Ssltotdh512keyexchanges                 int     `json:"ssltotdh512keyexchanges,omitempty"`
	Ssltotdhauthorizations                  int     `json:"ssltotdhauthorizations,omitempty"`
	Ssltotdssauthorizations                 int     `json:"ssltotdssauthorizations,omitempty"`
	Ssltotdtlsv12clientauthentications      int     `json:"ssltotdtlsv12clientauthentications,omitempty"`
	Ssltotdtlsv12handshakes                 int     `json:"ssltotdtlsv12handshakes,omitempty"`
	Ssltotdtlsv12renegsessions              int     `json:"ssltotdtlsv12renegsessions,omitempty"`
	Ssltotdtlsv12sessions                   int     `json:"ssltotdtlsv12sessions,omitempty"`
	Ssltotdtlsv12transactions               int     `json:"ssltotdtlsv12transactions,omitempty"`
	Ssltotdtlsv1clientauthentications       int     `json:"ssltotdtlsv1clientauthentications,omitempty"`
	Ssltotdtlsv1handshakes                  int     `json:"ssltotdtlsv1handshakes,omitempty"`
	Ssltotdtlsv1renegsessions               int     `json:"ssltotdtlsv1renegsessions,omitempty"`
	Ssltotdtlsv1sessions                    int     `json:"ssltotdtlsv1sessions,omitempty"`
	Ssltotdtlsv1transactions                int     `json:"ssltotdtlsv1transactions,omitempty"`
	Ssltotecdhe224keyexchanges              int     `json:"ssltotecdhe224keyexchanges,omitempty"`
	Ssltotecdhe256keyexchanges              int     `json:"ssltotecdhe256keyexchanges,omitempty"`
	Ssltotecdhe384keyexchanges              int     `json:"ssltotecdhe384keyexchanges,omitempty"`
	Ssltotecdhe521keyexchanges              int     `json:"ssltotecdhe521keyexchanges,omitempty"`
	Ssltotecdhetransactions                 int     `json:"ssltotecdhetransactions,omitempty"`
	Ssltotecdsaauthorizations               int     `json:"ssltotecdsaauthorizations,omitempty"`
	Ssltotenc                               int     `json:"ssltotenc,omitempty"`
	Ssltotencbe                             int     `json:"ssltotencbe,omitempty"`
	Ssltotencfe                             int     `json:"ssltotencfe,omitempty"`
	Ssltotenchw                             int     `json:"ssltotenchw,omitempty"`
	Ssltotenchwsecondary                    int     `json:"ssltotenchwsecondary,omitempty"`
	Ssltotencsw                             int     `json:"ssltotencsw,omitempty"`
	Ssltothwdecbe                           int     `json:"ssltothwdecbe,omitempty"`
	Ssltothwdecbesecondary                  int     `json:"ssltothwdecbesecondary,omitempty"`
	Ssltothwdecfe                           int     `json:"ssltothwdecfe,omitempty"`
	Ssltothwdecfesecondary                  int     `json:"ssltothwdecfesecondary,omitempty"`
	Ssltothwencbe                           int     `json:"ssltothwencbe,omitempty"`
	Ssltothwencbesecondary                  int     `json:"ssltothwencbesecondary,omitempty"`
	Ssltothwencfe                           int     `json:"ssltothwencfe,omitempty"`
	Ssltothwencfesecondary                  int     `json:"ssltothwencfesecondary,omitempty"`
	Ssltotmd5mac                            int     `json:"ssltotmd5mac,omitempty"`
	Ssltotnewsessions                       int     `json:"ssltotnewsessions,omitempty"`
	Ssltotnullauthorizations                int     `json:"ssltotnullauthorizations,omitempty"`
	Ssltotnullciphers                       int     `json:"ssltotnullciphers,omitempty"`
	Ssltotoffloadbulkaes                    int     `json:"ssltotoffloadbulkaes,omitempty"`
	Ssltotoffloadbulkaesgcm128              int     `json:"ssltotoffloadbulkaesgcm128,omitempty"`
	Ssltotoffloadbulkaesgcm256              int     `json:"ssltotoffloadbulkaesgcm256,omitempty"`
	Ssltotoffloadbulkdes                    int     `json:"ssltotoffloadbulkdes,omitempty"`
	Ssltotoffloadbulkrc4                    int     `json:"ssltotoffloadbulkrc4,omitempty"`
	Ssltotoffloaddhkeyexchanges             int     `json:"ssltotoffloaddhkeyexchanges,omitempty"`
	Ssltotoffloadrsakeyexchanges            int     `json:"ssltotoffloadrsakeyexchanges,omitempty"`
	Ssltotoffloadsignrsa                    int     `json:"ssltotoffloadsignrsa,omitempty"`
	Ssltotrenegsessions                     int     `json:"ssltotrenegsessions,omitempty"`
	Ssltotrsa1024keyexchanges               int     `json:"ssltotrsa1024keyexchanges,omitempty"`
	Ssltotrsa2048keyexchanges               int     `json:"ssltotrsa2048keyexchanges,omitempty"`
	Ssltotrsa3072keyexchanges               int     `json:"ssltotrsa3072keyexchanges,omitempty"`
	Ssltotrsa4096keyexchanges               int     `json:"ssltotrsa4096keyexchanges,omitempty"`
	Ssltotrsa512keyexchanges                int     `json:"ssltotrsa512keyexchanges,omitempty"`
	Ssltotrsaauthorizations                 int     `json:"ssltotrsaauthorizations,omitempty"`
	Ssltotsessionhits                       int     `json:"ssltotsessionhits,omitempty"`
	Ssltotsessionmiss                       int     `json:"ssltotsessionmiss,omitempty"`
	Ssltotsessions                          int     `json:"ssltotsessions,omitempty"`
	Ssltotsha256mac                         int     `json:"ssltotsha256mac,omitempty"`
	Ssltotsha384mac                         int     `json:"ssltotsha384mac,omitempty"`
	Ssltotshamac                            int     `json:"ssltotshamac,omitempty"`
	Ssltotsslserverinrecords                int     `json:"ssltotsslserverinrecords,omitempty"`
	Ssltotsslv2clientauthentications        int     `json:"ssltotsslv2clientauthentications,omitempty"`
	Ssltotsslv2handshakes                   int     `json:"ssltotsslv2handshakes,omitempty"`
	Ssltotsslv2sessions                     int     `json:"ssltotsslv2sessions,omitempty"`
	Ssltotsslv2transactions                 int     `json:"ssltotsslv2transactions,omitempty"`
	Ssltotsslv3clientauthentications        int     `json:"ssltotsslv3clientauthentications,omitempty"`
	Ssltotsslv3handshakes                   int     `json:"ssltotsslv3handshakes,omitempty"`
	Ssltotsslv3renegsessions                int     `json:"ssltotsslv3renegsessions,omitempty"`
	Ssltotsslv3sessions                     int     `json:"ssltotsslv3sessions,omitempty"`
	Ssltotsslv3transactions                 int     `json:"ssltotsslv3transactions,omitempty"`
	Ssltotswdecbe                           int     `json:"ssltotswdecbe,omitempty"`
	Ssltotswdecfe                           int     `json:"ssltotswdecfe,omitempty"`
	Ssltotswencbe                           int     `json:"ssltotswencbe,omitempty"`
	Ssltotswencfe                           int     `json:"ssltotswencfe,omitempty"`
	Ssltottlsv11clientauthentications       int     `json:"ssltottlsv11clientauthentications,omitempty"`
	Ssltottlsv11handshakes                  int     `json:"ssltottlsv11handshakes,omitempty"`
	Ssltottlsv11renegsessions               int     `json:"ssltottlsv11renegsessions,omitempty"`
	Ssltottlsv11sessions                    int     `json:"ssltottlsv11sessions,omitempty"`
	Ssltottlsv11transactions                int     `json:"ssltottlsv11transactions,omitempty"`
	Ssltottlsv12clientauthentications       int     `json:"ssltottlsv12clientauthentications,omitempty"`
	Ssltottlsv12handshakes                  int     `json:"ssltottlsv12handshakes,omitempty"`
	Ssltottlsv12renegsessions               int     `json:"ssltottlsv12renegsessions,omitempty"`
	Ssltottlsv12sessions                    int     `json:"ssltottlsv12sessions,omitempty"`
	Ssltottlsv12transactions                int     `json:"ssltottlsv12transactions,omitempty"`
	Ssltottlsv13clientauthentications       int     `json:"ssltottlsv13clientauthentications,omitempty"`
	Ssltottlsv13handshakes                  int     `json:"ssltottlsv13handshakes,omitempty"`
	Ssltottlsv13sessions                    int     `json:"ssltottlsv13sessions,omitempty"`
	Ssltottlsv13transactions                int     `json:"ssltottlsv13transactions,omitempty"`
	Ssltottlsv1clientauthentications        int     `json:"ssltottlsv1clientauthentications,omitempty"`
	Ssltottlsv1handshakes                   int     `json:"ssltottlsv1handshakes,omitempty"`
	Ssltottlsv1renegsessions                int     `json:"ssltottlsv1renegsessions,omitempty"`
	Ssltottlsv1sessions                     int     `json:"ssltottlsv1sessions,omitempty"`
	Ssltottlsv1transactions                 int     `json:"ssltottlsv1transactions,omitempty"`
	Ssltottransactions                      int     `json:"ssltottransactions,omitempty"`
	Ssltransactionsrate                     int     `json:"ssltransactionsrate,omitempty"`
}
