package lsn

type Lsndslitestats struct {
	Clearstats                   string `json:"clearstats,omitempty"`
	Lsncurdsliteicmpsessions     int    `json:"lsncurdsliteicmpsessions,omitempty"`
	Lsncurdsliteicmpsessionsrate int    `json:"lsncurdsliteicmpsessionsrate,omitempty"`
	Lsncurdslitesessions         int    `json:"lsncurdslitesessions,omitempty"`
	Lsncurdslitesessionsrate     int    `json:"lsncurdslitesessionsrate,omitempty"`
	Lsncurdslitetcpsessions      int    `json:"lsncurdslitetcpsessions,omitempty"`
	Lsncurdslitetcpsessionsrate  int    `json:"lsncurdslitetcpsessionsrate,omitempty"`
	Lsncurdsliteudpsessions      int    `json:"lsncurdsliteudpsessions,omitempty"`
	Lsncurdsliteudpsessionsrate  int    `json:"lsncurdsliteudpsessionsrate,omitempty"`
	Lsndslitecursubscribers      int    `json:"lsndslitecursubscribers,omitempty"`
	Lsndslitecursubscribersrate  int    `json:"lsndslitecursubscribersrate,omitempty"`
	Lsndsliteicmpdrppktsrate     int    `json:"lsndsliteicmpdrppktsrate,omitempty"`
	Lsndsliteicmprxbytesrate     int    `json:"lsndsliteicmprxbytesrate,omitempty"`
	Lsndsliteicmprxpktsrate      int    `json:"lsndsliteicmprxpktsrate,omitempty"`
	Lsndsliteicmptxbytesrate     int    `json:"lsndsliteicmptxbytesrate,omitempty"`
	Lsndsliteicmptxpktsrate      int    `json:"lsndsliteicmptxpktsrate,omitempty"`
	Lsndsliterxbytesrate         int    `json:"lsndsliterxbytesrate,omitempty"`
	Lsndsliterxpktsrate          int    `json:"lsndsliterxpktsrate,omitempty"`
	Lsndslitetcpdrppktsrate      int    `json:"lsndslitetcpdrppktsrate,omitempty"`
	Lsndslitetcprxbytesrate      int    `json:"lsndslitetcprxbytesrate,omitempty"`
	Lsndslitetcprxpktsrate       int    `json:"lsndslitetcprxpktsrate,omitempty"`
	Lsndslitetcptxbytesrate      int    `json:"lsndslitetcptxbytesrate,omitempty"`
	Lsndslitetcptxpktsrate       int    `json:"lsndslitetcptxpktsrate,omitempty"`
	Lsndslitetxbytesrate         int    `json:"lsndslitetxbytesrate,omitempty"`
	Lsndslitetxpktsrate          int    `json:"lsndslitetxpktsrate,omitempty"`
	Lsndsliteudpdrppktsrate      int    `json:"lsndsliteudpdrppktsrate,omitempty"`
	Lsndsliteudprxbytesrate      int    `json:"lsndsliteudprxbytesrate,omitempty"`
	Lsndsliteudprxpktsrate       int    `json:"lsndsliteudprxpktsrate,omitempty"`
	Lsndsliteudptxbytesrate      int    `json:"lsndsliteudptxbytesrate,omitempty"`
	Lsndsliteudptxpktsrate       int    `json:"lsndsliteudptxpktsrate,omitempty"`
	Lsntotdsliteicmpdrppkts      int    `json:"lsntotdsliteicmpdrppkts,omitempty"`
	Lsntotdsliteicmprxbytes      int    `json:"lsntotdsliteicmprxbytes,omitempty"`
	Lsntotdsliteicmprxpkts       int    `json:"lsntotdsliteicmprxpkts,omitempty"`
	Lsntotdsliteicmptxbytes      int    `json:"lsntotdsliteicmptxbytes,omitempty"`
	Lsntotdsliteicmptxpkts       int    `json:"lsntotdsliteicmptxpkts,omitempty"`
	Lsntotdsliterxbytes          int    `json:"lsntotdsliterxbytes,omitempty"`
	Lsntotdsliterxpkts           int    `json:"lsntotdsliterxpkts,omitempty"`
	Lsntotdslitetcpdrppkts       int    `json:"lsntotdslitetcpdrppkts,omitempty"`
	Lsntotdslitetcprxbytes       int    `json:"lsntotdslitetcprxbytes,omitempty"`
	Lsntotdslitetcprxpkts        int    `json:"lsntotdslitetcprxpkts,omitempty"`
	Lsntotdslitetcptxbytes       int    `json:"lsntotdslitetcptxbytes,omitempty"`
	Lsntotdslitetcptxpkts        int    `json:"lsntotdslitetcptxpkts,omitempty"`
	Lsntotdslitetxbytes          int    `json:"lsntotdslitetxbytes,omitempty"`
	Lsntotdslitetxpkts           int    `json:"lsntotdslitetxpkts,omitempty"`
	Lsntotdsliteudpdrppkts       int    `json:"lsntotdsliteudpdrppkts,omitempty"`
	Lsntotdsliteudprxbytes       int    `json:"lsntotdsliteudprxbytes,omitempty"`
	Lsntotdsliteudprxpkts        int    `json:"lsntotdsliteudprxpkts,omitempty"`
	Lsntotdsliteudptxbytes       int    `json:"lsntotdsliteudptxbytes,omitempty"`
	Lsntotdsliteudptxpkts        int    `json:"lsntotdsliteudptxpkts,omitempty"`
}
