package lsn

type Lsnnat64stats struct {
	Clearstats                  string `json:"clearstats,omitempty"`
	Lsncurnat64icmpsessions     int    `json:"lsncurnat64icmpsessions,omitempty"`
	Lsncurnat64icmpsessionsrate int    `json:"lsncurnat64icmpsessionsrate,omitempty"`
	Lsncurnat64sessions         int    `json:"lsncurnat64sessions,omitempty"`
	Lsncurnat64sessionsrate     int    `json:"lsncurnat64sessionsrate,omitempty"`
	Lsncurnat64tcpsessions      int    `json:"lsncurnat64tcpsessions,omitempty"`
	Lsncurnat64tcpsessionsrate  int    `json:"lsncurnat64tcpsessionsrate,omitempty"`
	Lsncurnat64udpsessions      int    `json:"lsncurnat64udpsessions,omitempty"`
	Lsncurnat64udpsessionsrate  int    `json:"lsncurnat64udpsessionsrate,omitempty"`
	Lsnnat64cursubscribers      int    `json:"lsnnat64cursubscribers,omitempty"`
	Lsnnat64cursubscribersrate  int    `json:"lsnnat64cursubscribersrate,omitempty"`
	Lsnnat64icmpdrppktsrate     int    `json:"lsnnat64icmpdrppktsrate,omitempty"`
	Lsnnat64icmprxbytesrate     int    `json:"lsnnat64icmprxbytesrate,omitempty"`
	Lsnnat64icmprxpktsrate      int    `json:"lsnnat64icmprxpktsrate,omitempty"`
	Lsnnat64icmptxbytesrate     int    `json:"lsnnat64icmptxbytesrate,omitempty"`
	Lsnnat64icmptxpktsrate      int    `json:"lsnnat64icmptxpktsrate,omitempty"`
	Lsnnat64rxbytesrate         int    `json:"lsnnat64rxbytesrate,omitempty"`
	Lsnnat64rxpktsrate          int    `json:"lsnnat64rxpktsrate,omitempty"`
	Lsnnat64tcpdrppktsrate      int    `json:"lsnnat64tcpdrppktsrate,omitempty"`
	Lsnnat64tcprxbytesrate      int    `json:"lsnnat64tcprxbytesrate,omitempty"`
	Lsnnat64tcprxpktsrate       int    `json:"lsnnat64tcprxpktsrate,omitempty"`
	Lsnnat64tcptxbytesrate      int    `json:"lsnnat64tcptxbytesrate,omitempty"`
	Lsnnat64tcptxpktsrate       int    `json:"lsnnat64tcptxpktsrate,omitempty"`
	Lsnnat64txbytesrate         int    `json:"lsnnat64txbytesrate,omitempty"`
	Lsnnat64txpktsrate          int    `json:"lsnnat64txpktsrate,omitempty"`
	Lsnnat64udpdrppktsrate      int    `json:"lsnnat64udpdrppktsrate,omitempty"`
	Lsnnat64udprxbytesrate      int    `json:"lsnnat64udprxbytesrate,omitempty"`
	Lsnnat64udprxpktsrate       int    `json:"lsnnat64udprxpktsrate,omitempty"`
	Lsnnat64udptxbytesrate      int    `json:"lsnnat64udptxbytesrate,omitempty"`
	Lsnnat64udptxpktsrate       int    `json:"lsnnat64udptxpktsrate,omitempty"`
	Lsntotnat64icmpdrppkts      int    `json:"lsntotnat64icmpdrppkts,omitempty"`
	Lsntotnat64icmprxbytes      int    `json:"lsntotnat64icmprxbytes,omitempty"`
	Lsntotnat64icmprxpkts       int    `json:"lsntotnat64icmprxpkts,omitempty"`
	Lsntotnat64icmptxbytes      int    `json:"lsntotnat64icmptxbytes,omitempty"`
	Lsntotnat64icmptxpkts       int    `json:"lsntotnat64icmptxpkts,omitempty"`
	Lsntotnat64rxbytes          int    `json:"lsntotnat64rxbytes,omitempty"`
	Lsntotnat64rxpkts           int    `json:"lsntotnat64rxpkts,omitempty"`
	Lsntotnat64tcpdrppkts       int    `json:"lsntotnat64tcpdrppkts,omitempty"`
	Lsntotnat64tcprxbytes       int    `json:"lsntotnat64tcprxbytes,omitempty"`
	Lsntotnat64tcprxpkts        int    `json:"lsntotnat64tcprxpkts,omitempty"`
	Lsntotnat64tcptxbytes       int    `json:"lsntotnat64tcptxbytes,omitempty"`
	Lsntotnat64tcptxpkts        int    `json:"lsntotnat64tcptxpkts,omitempty"`
	Lsntotnat64txbytes          int    `json:"lsntotnat64txbytes,omitempty"`
	Lsntotnat64txpkts           int    `json:"lsntotnat64txpkts,omitempty"`
	Lsntotnat64udpdrppkts       int    `json:"lsntotnat64udpdrppkts,omitempty"`
	Lsntotnat64udprxbytes       int    `json:"lsntotnat64udprxbytes,omitempty"`
	Lsntotnat64udprxpkts        int    `json:"lsntotnat64udprxpkts,omitempty"`
	Lsntotnat64udptxbytes       int    `json:"lsntotnat64udptxbytes,omitempty"`
	Lsntotnat64udptxpkts        int    `json:"lsntotnat64udptxpkts,omitempty"`
}
