package bot

type Botstats struct {
	Botreqbytes                          int    `json:"botreqbytes,omitempty"`
	Botreqbytesrate                      int    `json:"botreqbytesrate,omitempty"`
	Botrequests                          int    `json:"botrequests,omitempty"`
	Botrequestsrate                      int    `json:"botrequestsrate,omitempty"`
	Botresbytes                          int    `json:"botresbytes,omitempty"`
	Botresbytesrate                      int    `json:"botresbytesrate,omitempty"`
	Botresponses                         int    `json:"botresponses,omitempty"`
	Botresponsesrate                     int    `json:"botresponsesrate,omitempty"`
	Botviolblacklist                     int    `json:"botviolblacklist,omitempty"`
	Botviolblacklistdrop                 int    `json:"botviolblacklistdrop,omitempty"`
	Botviolblacklistdroprate             int    `json:"botviolblacklistdroprate,omitempty"`
	Botviolblacklistlog                  int    `json:"botviolblacklistlog,omitempty"`
	Botviolblacklistlograte              int    `json:"botviolblacklistlograte,omitempty"`
	Botviolblacklistrate                 int    `json:"botviolblacklistrate,omitempty"`
	Botviolblacklistredirect             int    `json:"botviolblacklistredirect,omitempty"`
	Botviolblacklistredirectrate         int    `json:"botviolblacklistredirectrate,omitempty"`
	Botviolblacklistreset                int    `json:"botviolblacklistreset,omitempty"`
	Botviolblacklistresetrate            int    `json:"botviolblacklistresetrate,omitempty"`
	Botviolcaptcha                       int    `json:"botviolcaptcha,omitempty"`
	Botviolcaptchadrop                   int    `json:"botviolcaptchadrop,omitempty"`
	Botviolcaptchadroprate               int    `json:"botviolcaptchadroprate,omitempty"`
	Botviolcaptchalog                    int    `json:"botviolcaptchalog,omitempty"`
	Botviolcaptchalograte                int    `json:"botviolcaptchalograte,omitempty"`
	Botviolcaptcharate                   int    `json:"botviolcaptcharate,omitempty"`
	Botviolcaptcharedirect               int    `json:"botviolcaptcharedirect,omitempty"`
	Botviolcaptcharedirectrate           int    `json:"botviolcaptcharedirectrate,omitempty"`
	Botviolcaptchareset                  int    `json:"botviolcaptchareset,omitempty"`
	Botviolcaptcharesetrate              int    `json:"botviolcaptcharesetrate,omitempty"`
	Botvioldevicefingerprint             int    `json:"botvioldevicefingerprint,omitempty"`
	Botvioldevicefingerprintcaptcha      int    `json:"botvioldevicefingerprintcaptcha,omitempty"`
	Botvioldevicefingerprintcaptcharate  int    `json:"botvioldevicefingerprintcaptcharate,omitempty"`
	Botvioldevicefingerprintdrop         int    `json:"botvioldevicefingerprintdrop,omitempty"`
	Botvioldevicefingerprintdroprate     int    `json:"botvioldevicefingerprintdroprate,omitempty"`
	Botvioldevicefingerprintlog          int    `json:"botvioldevicefingerprintlog,omitempty"`
	Botvioldevicefingerprintlograte      int    `json:"botvioldevicefingerprintlograte,omitempty"`
	Botvioldevicefingerprintrate         int    `json:"botvioldevicefingerprintrate,omitempty"`
	Botvioldevicefingerprintredirect     int    `json:"botvioldevicefingerprintredirect,omitempty"`
	Botvioldevicefingerprintredirectrate int    `json:"botvioldevicefingerprintredirectrate,omitempty"`
	Botvioldevicefingerprintreset        int    `json:"botvioldevicefingerprintreset,omitempty"`
	Botvioldevicefingerprintresetrate    int    `json:"botvioldevicefingerprintresetrate,omitempty"`
	Botviolipreputation                  int    `json:"botviolipreputation,omitempty"`
	Botviolipreputationcaptcha           int    `json:"botviolipreputationcaptcha,omitempty"`
	Botviolipreputationcaptcharate       int    `json:"botviolipreputationcaptcharate,omitempty"`
	Botviolipreputationdrop              int    `json:"botviolipreputationdrop,omitempty"`
	Botviolipreputationdroprate          int    `json:"botviolipreputationdroprate,omitempty"`
	Botviolipreputationlog               int    `json:"botviolipreputationlog,omitempty"`
	Botviolipreputationlograte           int    `json:"botviolipreputationlograte,omitempty"`
	Botviolipreputationrate              int    `json:"botviolipreputationrate,omitempty"`
	Botviolipreputationredirect          int    `json:"botviolipreputationredirect,omitempty"`
	Botviolipreputationredirectrate      int    `json:"botviolipreputationredirectrate,omitempty"`
	Botviolipreputationreset             int    `json:"botviolipreputationreset,omitempty"`
	Botviolipreputationresetrate         int    `json:"botviolipreputationresetrate,omitempty"`
	Botviolratelimit                     int    `json:"botviolratelimit,omitempty"`
	Botviolratelimitdrop                 int    `json:"botviolratelimitdrop,omitempty"`
	Botviolratelimitdroprate             int    `json:"botviolratelimitdroprate,omitempty"`
	Botviolratelimitlog                  int    `json:"botviolratelimitlog,omitempty"`
	Botviolratelimitlograte              int    `json:"botviolratelimitlograte,omitempty"`
	Botviolratelimitrate                 int    `json:"botviolratelimitrate,omitempty"`
	Botviolratelimitredirect             int    `json:"botviolratelimitredirect,omitempty"`
	Botviolratelimitredirectrate         int    `json:"botviolratelimitredirectrate,omitempty"`
	Botviolratelimitreset                int    `json:"botviolratelimitreset,omitempty"`
	Botviolratelimitresetrate            int    `json:"botviolratelimitresetrate,omitempty"`
	Botviolstaticsignature               int    `json:"botviolstaticsignature,omitempty"`
	Botviolstaticsignaturedrop           int    `json:"botviolstaticsignaturedrop,omitempty"`
	Botviolstaticsignaturedroprate       int    `json:"botviolstaticsignaturedroprate,omitempty"`
	Botviolstaticsignaturelog            int    `json:"botviolstaticsignaturelog,omitempty"`
	Botviolstaticsignaturelograte        int    `json:"botviolstaticsignaturelograte,omitempty"`
	Botviolstaticsignaturerate           int    `json:"botviolstaticsignaturerate,omitempty"`
	Botviolstaticsignatureredirect       int    `json:"botviolstaticsignatureredirect,omitempty"`
	Botviolstaticsignatureredirectrate   int    `json:"botviolstaticsignatureredirectrate,omitempty"`
	Botviolstaticsignaturereset          int    `json:"botviolstaticsignaturereset,omitempty"`
	Botviolstaticsignatureresetrate      int    `json:"botviolstaticsignatureresetrate,omitempty"`
	Botvioltps                           int    `json:"botvioltps,omitempty"`
	Botvioltpscaptcha                    int    `json:"botvioltpscaptcha,omitempty"`
	Botvioltpscaptcharate                int    `json:"botvioltpscaptcharate,omitempty"`
	Botvioltpsdrop                       int    `json:"botvioltpsdrop,omitempty"`
	Botvioltpsdroprate                   int    `json:"botvioltpsdroprate,omitempty"`
	Botvioltpslog                        int    `json:"botvioltpslog,omitempty"`
	Botvioltpslograte                    int    `json:"botvioltpslograte,omitempty"`
	Botvioltpsrate                       int    `json:"botvioltpsrate,omitempty"`
	Botvioltpsredirect                   int    `json:"botvioltpsredirect,omitempty"`
	Botvioltpsredirectrate               int    `json:"botvioltpsredirectrate,omitempty"`
	Botvioltpsreset                      int    `json:"botvioltpsreset,omitempty"`
	Botvioltpsresetrate                  int    `json:"botvioltpsresetrate,omitempty"`
	Botvioltrap                          int    `json:"botvioltrap,omitempty"`
	Botvioltrapdrop                      int    `json:"botvioltrapdrop,omitempty"`
	Botvioltrapdroprate                  int    `json:"botvioltrapdroprate,omitempty"`
	Botvioltraplog                       int    `json:"botvioltraplog,omitempty"`
	Botvioltraplograte                   int    `json:"botvioltraplograte,omitempty"`
	Botvioltraprate                      int    `json:"botvioltraprate,omitempty"`
	Botvioltrapredirect                  int    `json:"botvioltrapredirect,omitempty"`
	Botvioltrapredirectrate              int    `json:"botvioltrapredirectrate,omitempty"`
	Botvioltrapreset                     int    `json:"botvioltrapreset,omitempty"`
	Botvioltrapresetrate                 int    `json:"botvioltrapresetrate,omitempty"`
	Botviolwhitelist                     int    `json:"botviolwhitelist,omitempty"`
	Botviolwhitelistlog                  int    `json:"botviolwhitelistlog,omitempty"`
	Botviolwhitelistlograte              int    `json:"botviolwhitelistlograte,omitempty"`
	Botviolwhitelistrate                 int    `json:"botviolwhitelistrate,omitempty"`
	Clearstats                           string `json:"clearstats,omitempty"`
}
