package bot

type Botprofilestats struct {
	Botreqbytesperprofile                       int    `json:"botreqbytesperprofile,omitempty"`
	Botreqbytesperprofilerate                   int    `json:"botreqbytesperprofilerate,omitempty"`
	Botrequestsperprofile                       int    `json:"botrequestsperprofile,omitempty"`
	Botrequestsperprofilerate                   int    `json:"botrequestsperprofilerate,omitempty"`
	Botresbytesperprofile                       int    `json:"botresbytesperprofile,omitempty"`
	Botresbytesperprofilerate                   int    `json:"botresbytesperprofilerate,omitempty"`
	Botresponsesperprofile                      int    `json:"botresponsesperprofile,omitempty"`
	Botresponsesperprofilerate                  int    `json:"botresponsesperprofilerate,omitempty"`
	Botviolblacklistdropprofile                 int    `json:"botviolblacklistdropprofile,omitempty"`
	Botviolblacklistdropprofilerate             int    `json:"botviolblacklistdropprofilerate,omitempty"`
	Botviolblacklistlogprofile                  int    `json:"botviolblacklistlogprofile,omitempty"`
	Botviolblacklistlogprofilerate              int    `json:"botviolblacklistlogprofilerate,omitempty"`
	Botviolblacklistprofile                     int    `json:"botviolblacklistprofile,omitempty"`
	Botviolblacklistprofilerate                 int    `json:"botviolblacklistprofilerate,omitempty"`
	Botviolblacklistredirectprofile             int    `json:"botviolblacklistredirectprofile,omitempty"`
	Botviolblacklistredirectprofilerate         int    `json:"botviolblacklistredirectprofilerate,omitempty"`
	Botviolblacklistresetprofile                int    `json:"botviolblacklistresetprofile,omitempty"`
	Botviolblacklistresetprofilerate            int    `json:"botviolblacklistresetprofilerate,omitempty"`
	Botviolcaptchadropprofile                   int    `json:"botviolcaptchadropprofile,omitempty"`
	Botviolcaptchadropprofilerate               int    `json:"botviolcaptchadropprofilerate,omitempty"`
	Botviolcaptchalogprofile                    int    `json:"botviolcaptchalogprofile,omitempty"`
	Botviolcaptchalogprofilerate                int    `json:"botviolcaptchalogprofilerate,omitempty"`
	Botviolcaptchaprofile                       int    `json:"botviolcaptchaprofile,omitempty"`
	Botviolcaptchaprofilerate                   int    `json:"botviolcaptchaprofilerate,omitempty"`
	Botviolcaptcharedirectprofile               int    `json:"botviolcaptcharedirectprofile,omitempty"`
	Botviolcaptcharedirectprofilerate           int    `json:"botviolcaptcharedirectprofilerate,omitempty"`
	Botviolcaptcharesetprofile                  int    `json:"botviolcaptcharesetprofile,omitempty"`
	Botviolcaptcharesetprofilerate              int    `json:"botviolcaptcharesetprofilerate,omitempty"`
	Botvioldevicefingerprintcaptchaprofile      int    `json:"botvioldevicefingerprintcaptchaprofile,omitempty"`
	Botvioldevicefingerprintcaptchaprofilerate  int    `json:"botvioldevicefingerprintcaptchaprofilerate,omitempty"`
	Botvioldevicefingerprintdropprofile         int    `json:"botvioldevicefingerprintdropprofile,omitempty"`
	Botvioldevicefingerprintdropprofilerate     int    `json:"botvioldevicefingerprintdropprofilerate,omitempty"`
	Botvioldevicefingerprintlogprofile          int    `json:"botvioldevicefingerprintlogprofile,omitempty"`
	Botvioldevicefingerprintlogprofilerate      int    `json:"botvioldevicefingerprintlogprofilerate,omitempty"`
	Botvioldevicefingerprintprofile             int    `json:"botvioldevicefingerprintprofile,omitempty"`
	Botvioldevicefingerprintprofilerate         int    `json:"botvioldevicefingerprintprofilerate,omitempty"`
	Botvioldevicefingerprintredirectprofile     int    `json:"botvioldevicefingerprintredirectprofile,omitempty"`
	Botvioldevicefingerprintredirectprofilerate int    `json:"botvioldevicefingerprintredirectprofilerate,omitempty"`
	Botvioldevicefingerprintresetprofile        int    `json:"botvioldevicefingerprintresetprofile,omitempty"`
	Botvioldevicefingerprintresetprofilerate    int    `json:"botvioldevicefingerprintresetprofilerate,omitempty"`
	Botviolipreputationcaptchaprofile           int    `json:"botviolipreputationcaptchaprofile,omitempty"`
	Botviolipreputationcaptchaprofilerate       int    `json:"botviolipreputationcaptchaprofilerate,omitempty"`
	Botviolipreputationdropprofile              int    `json:"botviolipreputationdropprofile,omitempty"`
	Botviolipreputationdropprofilerate          int    `json:"botviolipreputationdropprofilerate,omitempty"`
	Botviolipreputationlogprofile               int    `json:"botviolipreputationlogprofile,omitempty"`
	Botviolipreputationlogprofilerate           int    `json:"botviolipreputationlogprofilerate,omitempty"`
	Botviolipreputationprofile                  int    `json:"botviolipreputationprofile,omitempty"`
	Botviolipreputationprofilerate              int    `json:"botviolipreputationprofilerate,omitempty"`
	Botviolipreputationredirectprofile          int    `json:"botviolipreputationredirectprofile,omitempty"`
	Botviolipreputationredirectprofilerate      int    `json:"botviolipreputationredirectprofilerate,omitempty"`
	Botviolipreputationresetprofile             int    `json:"botviolipreputationresetprofile,omitempty"`
	Botviolipreputationresetprofilerate         int    `json:"botviolipreputationresetprofilerate,omitempty"`
	Botviolratelimitdropprofile                 int    `json:"botviolratelimitdropprofile,omitempty"`
	Botviolratelimitdropprofilerate             int    `json:"botviolratelimitdropprofilerate,omitempty"`
	Botviolratelimitlogprofile                  int    `json:"botviolratelimitlogprofile,omitempty"`
	Botviolratelimitlogprofilerate              int    `json:"botviolratelimitlogprofilerate,omitempty"`
	Botviolratelimitprofile                     int    `json:"botviolratelimitprofile,omitempty"`
	Botviolratelimitprofilerate                 int    `json:"botviolratelimitprofilerate,omitempty"`
	Botviolratelimitredirectprofile             int    `json:"botviolratelimitredirectprofile,omitempty"`
	Botviolratelimitredirectprofilerate         int    `json:"botviolratelimitredirectprofilerate,omitempty"`
	Botviolratelimitresetprofile                int    `json:"botviolratelimitresetprofile,omitempty"`
	Botviolratelimitresetprofilerate            int    `json:"botviolratelimitresetprofilerate,omitempty"`
	Botviolstaticsignaturedropprofile           int    `json:"botviolstaticsignaturedropprofile,omitempty"`
	Botviolstaticsignaturedropprofilerate       int    `json:"botviolstaticsignaturedropprofilerate,omitempty"`
	Botviolstaticsignaturelogprofile            int    `json:"botviolstaticsignaturelogprofile,omitempty"`
	Botviolstaticsignaturelogprofilerate        int    `json:"botviolstaticsignaturelogprofilerate,omitempty"`
	Botviolstaticsignatureprofile               int    `json:"botviolstaticsignatureprofile,omitempty"`
	Botviolstaticsignatureprofilerate           int    `json:"botviolstaticsignatureprofilerate,omitempty"`
	Botviolstaticsignatureredirectprofile       int    `json:"botviolstaticsignatureredirectprofile,omitempty"`
	Botviolstaticsignatureredirectprofilerate   int    `json:"botviolstaticsignatureredirectprofilerate,omitempty"`
	Botviolstaticsignatureresetprofile          int    `json:"botviolstaticsignatureresetprofile,omitempty"`
	Botviolstaticsignatureresetprofilerate      int    `json:"botviolstaticsignatureresetprofilerate,omitempty"`
	Botvioltpscaptchaprofile                    int    `json:"botvioltpscaptchaprofile,omitempty"`
	Botvioltpscaptchaprofilerate                int    `json:"botvioltpscaptchaprofilerate,omitempty"`
	Botvioltpsdropprofile                       int    `json:"botvioltpsdropprofile,omitempty"`
	Botvioltpsdropprofilerate                   int    `json:"botvioltpsdropprofilerate,omitempty"`
	Botvioltpslogprofile                        int    `json:"botvioltpslogprofile,omitempty"`
	Botvioltpslogprofilerate                    int    `json:"botvioltpslogprofilerate,omitempty"`
	Botvioltpsprofile                           int    `json:"botvioltpsprofile,omitempty"`
	Botvioltpsprofilerate                       int    `json:"botvioltpsprofilerate,omitempty"`
	Botvioltpsredirectprofile                   int    `json:"botvioltpsredirectprofile,omitempty"`
	Botvioltpsredirectprofilerate               int    `json:"botvioltpsredirectprofilerate,omitempty"`
	Botvioltpsresetprofile                      int    `json:"botvioltpsresetprofile,omitempty"`
	Botvioltpsresetprofilerate                  int    `json:"botvioltpsresetprofilerate,omitempty"`
	Botvioltrapdropprofile                      int    `json:"botvioltrapdropprofile,omitempty"`
	Botvioltrapdropprofilerate                  int    `json:"botvioltrapdropprofilerate,omitempty"`
	Botvioltraplogprofile                       int    `json:"botvioltraplogprofile,omitempty"`
	Botvioltraplogprofilerate                   int    `json:"botvioltraplogprofilerate,omitempty"`
	Botvioltrapprofile                          int    `json:"botvioltrapprofile,omitempty"`
	Botvioltrapprofilerate                      int    `json:"botvioltrapprofilerate,omitempty"`
	Botvioltrapredirectprofile                  int    `json:"botvioltrapredirectprofile,omitempty"`
	Botvioltrapredirectprofilerate              int    `json:"botvioltrapredirectprofilerate,omitempty"`
	Botvioltrapresetprofile                     int    `json:"botvioltrapresetprofile,omitempty"`
	Botvioltrapresetprofilerate                 int    `json:"botvioltrapresetprofilerate,omitempty"`
	Botviolwhitelistlogprofile                  int    `json:"botviolwhitelistlogprofile,omitempty"`
	Botviolwhitelistlogprofilerate              int    `json:"botviolwhitelistlogprofilerate,omitempty"`
	Botviolwhitelistprofile                     int    `json:"botviolwhitelistprofile,omitempty"`
	Botviolwhitelistprofilerate                 int    `json:"botviolwhitelistprofilerate,omitempty"`
	Clearstats                                  string `json:"clearstats,omitempty"`
	Name                                        string `json:"name,omitempty"`
}
